/*

 Copyright (C) 2004-2009 Alex Gorbatchev.

 @license
 This file is part of SyntaxHighlighter.

 SyntaxHighlighter is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 SyntaxHighlighter is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with SyntaxHighlighter.  If not, see <http://www.gnu.org/copyleft/lesser.html>.
*/
if(!window.SyntaxHighlighter)var SyntaxHighlighter=function(){var e={defaults:{"class-name":"","first-line":1,"pad-line-numbers":!0,highlight:null,"smart-tabs":!0,"tab-size":4,gutter:!0,toolbar:!0,collapse:!1,"auto-links":!0,light:!1,"wrap-lines":!0,"html-script":!1},config:{useScriptTags:!0,clipboardSwf:null,toolbarItemWidth:16,toolbarItemHeight:16,bloggerMode:!1,stripBrs:!1,tagName:"pre",strings:{expandSource:"show source",viewSource:"view source",copyToClipboard:"copy to clipboard",copyToClipboardConfirmation:"The code is in your clipboard now",
print:"print",help:"?",alert:"SyntaxHighlighter\n\n",noBrush:"Can't find brush for: ",brushNotHtmlScript:"Brush wasn't configured for html-script option: ",aboutDialog:'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>About SyntaxHighlighter</title></head><body style="font-family:Geneva,Arial,Helvetica,sans-serif;background-color:#fff;color:#000;font-size:1em;text-align:center;"><div style="text-align:center;margin-top:3em;"><div style="font-size:xx-large;">SyntaxHighlighter</div><div style="font-size:.75em;margin-bottom:4em;"><div>version 2.1.382 (June 24 2010)</div><div><a href="http://alexgorbatchev.com" target="_blank" style="color:#0099FF;text-decoration:none;">http://alexgorbatchev.com</a></div><div>If you like this script, please <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2930402" style="color:#0099FF;text-decoration:none;">donate</a> to keep development active!</div></div><div>JavaScript code syntax highlighter.</div><div>Copyright 2004-2009 Alex Gorbatchev.</div></div></body></html>'},
debug:!1},vars:{discoveredBrushes:null,spaceWidth:null,printFrame:null,highlighters:{}},brushes:{},regexLib:{multiLineCComments:/\/\*[\s\S]*?\*\//gm,singleLineCComments:/\/\/.*$/gm,singleLinePerlComments:/#.*$/gm,doubleQuotedString:/"([^\\"\n]|\\.)*"/g,singleQuotedString:/'([^\\'\n]|\\.)*'/g,multiLineDoubleQuotedString:/"([^\\"]|\\.)*"/g,multiLineSingleQuotedString:/'([^\\']|\\.)*'/g,xmlComments:/(&lt;|<)!--[\s\S]*?--(&gt;|>)/gm,url:/&lt;\w+:\/\/[\w-.\/?%&=@:;]*&gt;|\w+:\/\/[\w-.\/?%&=@:;]*/g,phpScriptTags:{left:/(&lt;|<)\?(?:=|php)?/g,
right:/\?(&gt;|>)/g,eof_end:!0},aspScriptTags:{left:/(&lt;|<)%=?/g,right:/%(&gt;|>)/g},scriptScriptTags:{left:/(&lt;|<)\s*script.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*script\s*(&gt;|>)/gi}},toolbar:{create:function(a){var b=document.createElement("DIV"),c=e.toolbar.items;b.className="toolbar";for(var d in c){var g=new c[d](a),f=g.create();a.toolbarCommands[d]=g;null!=f&&("string"==typeof f&&(f=e.toolbar.createButton(f,a.id,d)),f.className+="item "+d,b.appendChild(f))}return b},createButton:function(a,
b,c){var d=document.createElement("a"),g=d.style,f=e.config,k=f.toolbarItemWidth,f=f.toolbarItemHeight;d.href="#"+c;d.title=a;d.highlighterId=b;d.commandName=c;d.innerHTML=a;!1==isNaN(k)&&(g.width=k+"px");!1==isNaN(f)&&(g.height=f+"px");d.onclick=function(a){try{e.toolbar.executeCommand(this,a||window.event,this.highlighterId,this.commandName)}catch(b){e.utils.alert(b.message)}return!1};return d},executeCommand:function(a,b,c,d,g){c=e.vars.highlighters[c];var f;return null==c||null==(f=c.toolbarCommands[d])?
null:f.execute(a,b,g)},items:{expandSource:function(a){this.create=function(){if(!0==a.getParam("collapse"))return e.config.strings.expandSource};this.execute=function(b,c,d){c=a.div;b.parentNode.removeChild(b);c.className=c.className.replace("collapsed","")}},viewSource:function(a){this.create=function(){return e.config.strings.viewSource};this.execute=function(b,c,d){b=e.utils.fixInputString(a.originalCode).replace(/</g,"&lt;");c=e.utils.popup("","_blank",750,400,"location=0, resizable=1, menubar=0, scrollbars=1");
b=e.utils.unindent(b);c.document.write("<pre>"+b+"</pre>");c.document.close()}},copyToClipboard:function(a){var b,c=a.id;this.create=function(){function a(b){var c="",d;for(d in b)c+="<param name='"+d+"' value='"+b[d]+"'/>";return c}function g(a){var b="",c;for(c in a)b+=" "+c+"='"+a[c]+"'";return b}var f=e.config;if(null==f.clipboardSwf)return null;var k={width:f.toolbarItemWidth,height:f.toolbarItemHeight,id:c+"_clipboard",type:"application/x-shockwave-flash",title:e.config.strings.copyToClipboard},
h={allowScriptAccess:"always",wmode:"transparent",flashVars:"highlighterId="+c,menu:"false"},f=f.clipboardSwf,k=/msie/i.test(navigator.userAgent)?"<object"+g({classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0"})+g(k)+">"+a(h)+a({movie:f})+"</object>":"<embed"+g(k)+g(h)+g({src:f})+"/>";b=document.createElement("div");b.innerHTML=k;return b};this.execute=function(b,c,f){switch(f.command){case "get":if(b=
e.utils.unindent(e.utils.fixInputString(a.originalCode).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")),window.clipboardData)window.clipboardData.setData("text",b);else return e.utils.unindent(b);case "ok":e.utils.alert(e.config.strings.copyToClipboardConfirmation);break;case "error":e.utils.alert(f.message)}}},printSource:function(a){this.create=function(){return e.config.strings.print};this.execute=function(b,c,d){b=document.createElement("IFRAME");c=null;null!=e.vars.printFrame&&
document.body.removeChild(e.vars.printFrame);e.vars.printFrame=b;b.style.cssText="position:absolute;width:0px;height:0px;left:-500px;top:-500px;";document.body.appendChild(b);d=c=b.contentWindow.document;for(var g=window.document.getElementsByTagName("link"),f=0;f<g.length;f++)"stylesheet"==g[f].rel.toLowerCase()&&/shCore\.css$/.test(g[f].href)&&d.write('<link type="text/css" rel="stylesheet" href="'+g[f].href+'"></link>');c.write('<div class="'+a.div.className.replace("collapsed","")+' printing">'+
a.div.innerHTML+"</div>");c.close();b.contentWindow.focus();b.contentWindow.print()}},about:function(a){this.create=function(){return e.config.strings.help};this.execute=function(a,c){var d=e.utils.popup("","_blank",500,250,"scrollbars=0"),g=d.document;g.write(e.config.strings.aboutDialog);g.close();d.focus()}}}},utils:{indexOf:function(a,b,c){for(c=Math.max(c||0,0);c<a.length;c++)if(a[c]==b)return c;return-1},guid:function(a){return a+Math.round(1E6*Math.random()).toString()},merge:function(a,b){var c=
{},d;for(d in a)c[d]=a[d];for(d in b)c[d]=b[d];return c},toBoolean:function(a){switch(a){case "true":return!0;case "false":return!1}return a},popup:function(a,b,c,d,e){e+=", left="+(screen.width-c)/2+", top="+(screen.height-d)/2+", width="+c+", height="+d;e=e.replace(/^,/,"");a=window.open(a,b,e);a.focus();return a},addEvent:function(a,b,c){a.attachEvent?(a["e"+b+c]=c,a[b+c]=function(){a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c])):a.addEventListener(b,c,!1)},alert:function(a){alert(e.config.strings.alert+
a)},findBrush:function(a,b){var c=e.vars.discoveredBrushes,d=null;if(null==c){var c={},g;for(g in e.brushes)if(d=e.brushes[g].aliases,null!=d){e.brushes[g].name=g.toLowerCase();for(var f=0;f<d.length;f++)c[d[f]]=g}e.vars.discoveredBrushes=c}d=e.brushes[c[a]];null==d&&!1!=b&&e.utils.alert(e.config.strings.noBrush+a);return d},eachLine:function(a,b){for(var c=a.split("\n"),d=0;d<c.length;d++)c[d]=b(c[d]);return c.join("\n")},trimFirstAndLastLines:function(a){return a.replace(/^[ ]*[\n]+|[\n]*[ ]*$/g,
"")},parseParams:function(a){for(var b,c={},d=new XRegExp("^\\[(?<values>(.*?))\\]$"),e=new XRegExp("(?<name>[\\w-]+)\\s*:\\s*(?<value>[\\w-%#]+|\\[.*?\\]|\".*?\"|'.*?')\\s*;?","g");null!=(b=e.exec(a));){var f=b.value.replace(/^['"]|['"]$/g,"");null!=f&&d.test(f)&&(f=d.exec(f),f=0<f.values.length?f.values.split(/\s*,\s*/):[]);c[b.name]=f}return c},decorate:function(a,b){if(null==a||0==a.length||"\n"==a)return a;a=a.replace(/</g,"&lt;");a=a.replace(/ {2,}/g,function(a){for(var b="",e=0;e<a.length-
1;e++)b+="&nbsp;";return b+" "});null!=b&&(a=e.utils.eachLine(a,function(a){if(0==a.length)return"";var d="";a=a.replace(/^(&nbsp;| )+/,function(a){d=a;return""});return 0==a.length?d:d+'<code class="'+b+'">'+a+"</code>"}));return a},padNumber:function(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c},measureSpace:function(){var a=document.createElement("div"),b;b=0;var c=document.body;b=e.utils.guid("measureSpace");a.innerHTML='<div class="syntaxhighlighter"><div class="lines"><div class="line"><div class="content"><span class="block"><span id="'+
b+'">&nbsp;</span></span></div></div></div></div>';c.appendChild(a);b=document.getElementById(b);/opera/i.test(navigator.userAgent)?(b=window.getComputedStyle(b,null),b=parseInt(b.getPropertyValue("width"))):b=b.offsetWidth;c.removeChild(a);return b},processTabs:function(a,b){for(var c="",d=0;d<b;d++)c+=" ";return a.replace(/\t/g,c)},processSmartTabs:function(a,b){a.split("\n");for(var c="",d=0;50>d;d++)c+="\t\t\t\t\t";return a=e.utils.eachLine(a,function(a){if(-1==a.indexOf("\t"))return a;for(var d=
0;-1!=(d=a.indexOf("\t"));){var e=d,d=b-d%b;a=a.substr(0,e)+c.substr(0,d)+a.substr(e+1,a.length)}return a})},fixInputString:function(a){var b=/<br\s*\/?>|&lt;br\s*\/?&gt;/gi;!0==e.config.bloggerMode&&(a=a.replace(b,"\n"));!0==e.config.stripBrs&&(a=a.replace(b,""));return a},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},unindent:function(a){for(var b=e.utils.fixInputString(a).split("\n"),c=/^\s*/,d=1E3,g=0;g<b.length&&0<d;g++){var f=b[g];if(0!=e.utils.trim(f).length){f=c.exec(f);if(null==f)return a;
d=Math.min(f[0].length,d)}}if(0<d)for(g=0;g<b.length;g++)b[g]=b[g].substr(d);return b.join("\n")},matchesSortCallback:function(a,b){return a.index<b.index?-1:a.index>b.index?1:a.length<b.length?-1:a.length>b.length?1:0},getMatches:function(a,b){function c(a,b){return[new e.Match(a[0],a.index,b.css)]}for(var d=null,g=[],f=b.func?b.func:c;null!=(d=b.regex.exec(a));)g=g.concat(f(d,b));return g},processUrls:function(a){return a.replace(e.regexLib.url,function(a){var c="",d="";0==a.indexOf("&lt;")&&(d=
"&lt;",a=a.substring(4));a.indexOf("&gt;")==a.length-4&&(a=a.substring(0,a.length-4),c="&gt;");return d+'<a href="'+a+'">'+a+"</a>"+c})},getSyntaxHighlighterScriptTags:function(){for(var a=document.getElementsByTagName("script"),b=[],c=0;c<a.length;c++)"syntaxhighlighter"==a[c].type&&b.push(a[c]);return b},stripCData:function(a){var b=e.utils.trim(a),c=!1;0==b.indexOf("<![CDATA[")&&(b=b.substring(9),c=!0);b.indexOf("]]\x3e")==b.length-3&&(b=b.substring(0,b.length-3),c=!0);return c?b:a}},highlight:function(a,
b){var c;if(b)c=[b];else{c=document.getElementsByTagName(e.config.tagName);for(var d=[],g=0;g<c.length;g++)d.push(c[g]);c=d}var f=null,d=e.config;d.useScriptTags&&(c=c.concat(e.utils.getSyntaxHighlighterScriptTags()));if(0!==c.length)for(g=0;g<c.length;g++){var k=c[g],h=e.utils.parseParams(k.className),m,l,h=e.utils.merge(a,h);m=h.brush;if(null!=m){if("true"==h["html-script"]||!0==e.defaults["html-script"])f=new e.HtmlScript(m),m="htmlscript";else if(f=e.utils.findBrush(m))m=f.name,f=new f;else continue;
l=k.innerHTML;d.useScriptTags&&(l=e.utils.stripCData(l));h["brush-name"]=m;f.highlight(l,h);h=f.div;e.config.debug&&(h=document.createElement("textarea"),h.value=f.div.innerHTML,h.style.width="70em",h.style.height="30em");k.parentNode.replaceChild(h,k)}}},all:function(a){e.utils.addEvent(window,"load",function(){e.highlight(a)})},Match:function(a,b,c){this.value=a;this.index=b;this.length=a.length;this.css=c;this.brushName=null}};e.Match.prototype.toString=function(){return this.value};e.HtmlScript=
function(a){function b(a,b){for(var c=0;c<a.length;c++)a[c].index+=b}function c(a,c){for(var f=a.code,l=[],t=g.regexList,s=a.index+a.left.length,q=g.htmlScript,r,p=0;p<t.length;p++)r=e.utils.getMatches(f,t[p]),b(r,s),l=l.concat(r);null!=q.left&&null!=a.left&&(r=e.utils.getMatches(a.left,q.left),b(r,a.index),l=l.concat(r));null!=q.right&&null!=a.right&&(r=e.utils.getMatches(a.right,q.right),b(r,a.index+a[0].lastIndexOf(a.right)),l=l.concat(r));for(f=0;f<l.length;f++)l[f].brushName=d.name;return l}
var d=e.utils.findBrush(a),g,f=new e.brushes.Xml;null!=d&&(g=new d,this.xmlBrush=f,null==g.htmlScript?e.utils.alert(e.config.strings.brushNotHtmlScript+a):f.regexList.push({regex:g.htmlScript.code,func:c}))};e.HtmlScript.prototype.highlight=function(a,b){this.xmlBrush.highlight(a,b);this.div=this.xmlBrush.div};e.Highlighter=function(){};e.Highlighter.prototype={getParam:function(a,b){var c=this.params[a];return e.utils.toBoolean(null==c?b:c)},create:function(a){return document.createElement(a)},findMatches:function(a,
b){var c=[];if(null!=a)for(var d=0;d<a.length;d++)"object"==typeof a[d]&&(c=c.concat(e.utils.getMatches(b,a[d])));return c.sort(e.utils.matchesSortCallback)},removeNestedMatches:function(){for(var a=this.matches,b=0;b<a.length;b++)if(null!==a[b])for(var c=a[b],d=c.index+c.length,e=b+1;e<a.length&&null!==a[b];e++){var f=a[e];if(null!==f)if(f.index>d)break;else f.index==c.index&&f.length>c.length?this.matches[b]=null:f.index>=c.index&&f.index<d&&(this.matches[e]=null)}},createDisplayLines:function(a){var b=
a.split("\n"),c=parseInt(this.getParam("first-line")),d=this.getParam("pad-line-numbers"),g=this.getParam("highlight",[]),f=this.getParam("gutter");a="";!0==d?d=(c+b.length-1).toString().length:!0==isNaN(d)&&(d=0);for(var k=0;k<b.length;k++){var h=b[k],m=/^(&nbsp;|\s)+/.exec(h),l="alt"+(0==k%2?1:2),t=e.utils.padNumber(c+k,d),s=-1!=e.utils.indexOf(g,(c+k).toString()),q=null;null!=m&&(q=m[0].toString(),h=h.substr(q.length));h=e.utils.trim(h);0==h.length&&(h="&nbsp;");s&&(l+=" highlighted");a+='<div class="line '+
l+'"><table><tr>'+(f?'<td class="number"><code>'+t+"</code></td>":"")+'<td class="content">'+(null!=q?'<code class="spaces">'+q.replace(" ","&nbsp;")+"</code>":"")+h+"</td></tr></table></div>"}return a},processMatches:function(a,b){function c(a){return(a=a?a.brushName||k:k)?a+" ":""}for(var d=0,g="",f=e.utils.decorate,k=this.getParam("brush-name",""),h=0;h<b.length;h++){var m=b[h],l;null!==m&&0!==m.length&&(l=c(m),g+=f(a.substr(d,m.index-d),l+"plain")+f(m.value,l+m.css),d=m.index+m.length)}return g+=
f(a.substr(d),c()+"plain")},highlight:function(a,b){var c=e.vars,d;this.params={};this.bar=this.code=this.lines=this.div=null;this.toolbarCommands={};this.id=e.utils.guid("highlighter_");c.highlighters[this.id]=this;null===a&&(a="");this.params=e.utils.merge(e.defaults,b||{});!0==this.getParam("light")&&(this.params.toolbar=this.params.gutter=!1);this.div=c=this.create("DIV");this.lines=this.create("DIV");this.lines.className="lines";className="syntaxhighlighter";c.id=this.id;this.getParam("collapse")&&
(className+=" collapsed");!1==this.getParam("gutter")&&(className+=" nogutter");!1==this.getParam("wrap-lines")&&(this.lines.className+=" no-wrap");className+=" "+this.getParam("class-name");className+=" "+this.getParam("brush-name");c.className=className;this.originalCode=a;this.code=e.utils.trimFirstAndLastLines(a).replace(/\r/g," ");d=this.getParam("tab-size");this.code=!0==this.getParam("smart-tabs")?e.utils.processSmartTabs(this.code,d):e.utils.processTabs(this.code,d);this.code=e.utils.unindent(this.code);
if(this.getParam("toolbar")){this.bar=this.create("DIV");this.bar.className="bar";this.bar.appendChild(e.toolbar.create(this));c.appendChild(this.bar);var g=this.bar,f=function(){g.className=g.className.replace("show","")};c.onmouseover=function(){f();g.className+=" show"};c.onmouseout=function(){f()}}c.appendChild(this.lines);this.matches=this.findMatches(this.regexList,this.code);this.removeNestedMatches();a=this.processMatches(this.code,this.matches);a=this.createDisplayLines(e.utils.trim(a));
this.getParam("auto-links")&&(a=e.utils.processUrls(a));this.lines.innerHTML=a},getKeywords:function(a){a=a.replace(/^\s+|\s+$/g,"").replace(/\s+/g,"|");return"\\b(?:"+a+")\\b"},forHtmlScript:function(a){var b=a.right.source;a.eof_end&&(b="(?:(?:"+b+")|$)");this.htmlScript={left:{regex:a.left,css:"script"},right:{regex:a.right,css:"script"},code:new XRegExp("(?<left>"+a.left.source+")(?<code>.*?)(?<right>"+b+")","sgi")}}};return e}();
window.XRegExp||function(){var e=RegExp.prototype.exec,a=String.prototype.replace,b=/(?:[^\\([#\s.]+|\\(?!k<[\w$]+>|[pP]{[^}]+})[\S\s]?|\((?=\?(?!#|<[\w$]+>)))+|(\()(?:\?(?:(#)[^)]*\)|<([$\w]+)>))?|\\(?:k<([\w$]+)>|[pP]{([^}]+)})|(\[\^?)|([\S\s])/g,c=/^(?:\s+|#.*)+/,d=/^(?:[?*+]|{\d+(?:,\d*)?})/,g=/&&\[\^?/g,f=/]/g,k=void 0!==/()??/.exec("")[1],h={};XRegExp=function(m,l){if(m instanceof RegExp){if(void 0!==l)throw TypeError("can't supply flags when constructing one RegExp from another");return m.addFlags()}l=
l||"";var k=-1<l.indexOf("s"),s=-1<l.indexOf("x"),q=!1,r=[],p=[],n,u;for(b.lastIndex=0;n=e.call(b,m);)if(n[2])d.test(m.slice(b.lastIndex))||p.push("(?:)");else if(n[1])r.push(n[3]||null),n[3]&&(q=!0),p.push("(");else if(n[4]){a:{for(u=0;u<r.length;u++)if(r[u]===n[4])break a;u=-1}p.push(-1<u?"\\"+(u+1)+(isNaN(m.charAt(b.lastIndex))?"":"(?:)"):n[0])}else n[5]?p.push(h.unicode?h.unicode.get(n[5],"P"===n[0].charAt(1)):n[0]):n[6]?"]"===m.charAt(b.lastIndex)?(p.push("["===n[6]?"(?!)":"[\\S\\s]"),b.lastIndex++):
(u=XRegExp.matchRecursive("&&"+m.slice(n.index),g,f,"",{escapeChar:"\\"})[0],p.push(n[6]+u+"]"),b.lastIndex+=u.length+1):n[7]?k&&"."===n[7]?p.push("[\\S\\s]"):s&&c.test(n[7])?(n=e.call(c,m.slice(b.lastIndex-1))[0].length,d.test(m.slice(b.lastIndex-1+n))||p.push("(?:)"),b.lastIndex+=n-1):p.push(n[7]):p.push(n[0]);k=RegExp(p.join(""),a.call(l,/[sx]+/g,""));k._x={source:m,captureNames:q?r:null};return k};XRegExp.addPlugin=function(a,b){h[a]=b};RegExp.prototype.exec=function(b){var c=e.call(this,b),d;
if(c){k&&1<c.length&&(b=RegExp("^"+this.source+"$(?!\\s)",this.getNativeFlags()),a.call(c[0],b,function(){for(d=1;d<arguments.length-2;d++)void 0===arguments[d]&&(c[d]=void 0)}));if(this._x&&this._x.captureNames)for(d=1;d<c.length;d++)(b=this._x.captureNames[d-1])&&(c[b]=c[d]);this.global&&this.lastIndex>c.index+c[0].length&&this.lastIndex--}return c}}();
RegExp.prototype.getNativeFlags=function(){return(this.global?"g":"")+(this.ignoreCase?"i":"")+(this.multiline?"m":"")+(this.extended?"x":"")+(this.sticky?"y":"")};RegExp.prototype.addFlags=function(e){e=new XRegExp(this.source,(e||"")+this.getNativeFlags());this._x&&(e._x={source:this._x.source,captureNames:this._x.captureNames?this._x.captureNames.slice(0):null});return e};RegExp.prototype.call=function(e,a){return this.exec(a)};RegExp.prototype.apply=function(e,a){return this.exec(a[0])};
XRegExp.cache=function(e,a){var b="/"+e+"/"+(a||"");return XRegExp.cache[b]||(XRegExp.cache[b]=new XRegExp(e,a))};XRegExp.escape=function(e){return e.replace(/[-[\]{}()*+?.\\^$|,#\s]/g,"\\$&")};
XRegExp.matchRecursive=function(e,a,b,c,d){d=d||{};var g=d.escapeChar;d=d.valueNames;c=c||"";var f=-1<c.indexOf("g"),k=-1<c.indexOf("i"),h=-1<c.indexOf("m"),m=-1<c.indexOf("y");c=c.replace(/y/g,"");a=a instanceof RegExp?a.global?a:a.addFlags("g"):new XRegExp(a,"g"+c);b=b instanceof RegExp?b.global?b:b.addFlags("g"):new XRegExp(b,"g"+c);c=[];var l=0,t=0,s=0,q=0,r,p,n;if(g){if(1<g.length)throw SyntaxError("can't supply more than one escape character");if(h)throw TypeError("can't supply escape character when using the multiline flag");
n=XRegExp.escape(g);n=RegExp("^(?:"+n+"[\\S\\s]|(?:(?!"+a.source+"|"+b.source+")[^"+n+"])+)+",k?"i":"")}for(;;){a.lastIndex=b.lastIndex=s+(g?(n.exec(e.slice(s))||[""])[0].length:0);k=a.exec(e);h=b.exec(e);k&&h&&(k.index<=h.index?h=null:k=null);if(k||h)t=(k||h).index,s=(k?a:b).lastIndex;else if(!l)break;if(m&&!l&&t>q)break;if(k)l++||(r=t,p=s);else if(h&&l){if(!--l&&(d?(d[0]&&r>q&&c.push([d[0],e.slice(q,r),q,r]),d[1]&&c.push([d[1],e.slice(r,p),r,p]),d[2]&&c.push([d[2],e.slice(p,t),p,t]),d[3]&&c.push([d[3],
e.slice(t,s),t,s])):c.push(e.slice(p,t)),q=s,!f))break}else throw a.lastIndex=b.lastIndex=0,Error("subject data contains unbalanced delimiters");t===s&&s++}f&&!m&&d&&d[0]&&e.length>q&&c.push([d[0],e.slice(q),q,e.length]);a.lastIndex=b.lastIndex=0;return c};