/**
 * SyntaxHighlighter
 * http://alexgorbatchev.com/
 *
 * SyntaxHighlighter is donationware. If you are using it, please donate.
 * http://alexgorbatchev.com/wiki/SyntaxHighlighter:Donate
 *
 * @version
 * 2.1.382 (June 24 2010)
 * 
 * @copyright
 * Copyright (C) 2004-2009 Alex Gorbatchev.
 *
 * @license
 * This file is part of SyntaxHighlighter.
 * 
 * SyntaxHighlighter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SyntaxHighlighter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SyntaxHighlighter.  If not, see <http://www.gnu.org/copyleft/lesser.html>.
 */
if(!window.SyntaxHighlighter)var SyntaxHighlighter=function(){var d={defaults:{"class-name":"","first-line":1,"pad-line-numbers":!0,highlight:null,"smart-tabs":!0,"tab-size":4,gutter:!0,toolbar:!0,collapse:!1,"auto-links":!0,light:!1,"wrap-lines":!0,"html-script":!1},config:{useScriptTags:!0,clipboardSwf:null,toolbarItemWidth:16,toolbarItemHeight:16,bloggerMode:!1,stripBrs:!1,tagName:"pre",strings:{expandSource:"show source",viewSource:"view source",copyToClipboard:"copy to clipboard",copyToClipboardConfirmation:"The code is in your clipboard now",
print:"print",help:"?",alert:"SyntaxHighlighter\n\n",noBrush:"Can't find brush for: ",brushNotHtmlScript:"Brush wasn't configured for html-script option: ",aboutDialog:'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>About SyntaxHighlighter</title></head><body style="font-family:Geneva,Arial,Helvetica,sans-serif;background-color:#fff;color:#000;font-size:1em;text-align:center;"><div style="text-align:center;margin-top:3em;"><div style="font-size:xx-large;">SyntaxHighlighter</div><div style="font-size:.75em;margin-bottom:4em;"><div>version 2.1.382 (June 24 2010)</div><div><a href="http://alexgorbatchev.com" target="_blank" style="color:#0099FF;text-decoration:none;">http://alexgorbatchev.com</a></div><div>If you like this script, please <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2930402" style="color:#0099FF;text-decoration:none;">donate</a> to keep development active!</div></div><div>JavaScript code syntax highlighter.</div><div>Copyright 2004-2009 Alex Gorbatchev.</div></div></body></html>'},
debug:!1},vars:{discoveredBrushes:null,spaceWidth:null,printFrame:null,highlighters:{}},brushes:{},regexLib:{multiLineCComments:/\/\*[\s\S]*?\*\//gm,singleLineCComments:/\/\/.*$/gm,singleLinePerlComments:/#.*$/gm,doubleQuotedString:/"([^\\"\n]|\\.)*"/g,singleQuotedString:/'([^\\'\n]|\\.)*'/g,multiLineDoubleQuotedString:/"([^\\"]|\\.)*"/g,multiLineSingleQuotedString:/'([^\\']|\\.)*'/g,xmlComments:/(&lt;|<)!--[\s\S]*?--(&gt;|>)/gm,url:/&lt;\w+:\/\/[\w-.\/?%&=@:;]*&gt;|\w+:\/\/[\w-.\/?%&=@:;]*/g,phpScriptTags:{left:/(&lt;|<)\?=?/g,
right:/\?(&gt;|>)/g},aspScriptTags:{left:/(&lt;|<)%=?/g,right:/%(&gt;|>)/g},scriptScriptTags:{left:/(&lt;|<)\s*script.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*script\s*(&gt;|>)/gi}},toolbar:{create:function(a){var b=document.createElement("DIV"),c=d.toolbar.items;b.className="toolbar";for(var e in c){var g=new c[e](a),f=g.create();a.toolbarCommands[e]=g;f!=null&&(typeof f=="string"&&(f=d.toolbar.createButton(f,a.id,e)),f.className+="item "+e,b.appendChild(f))}return b},createButton:function(a,b,c){var e=
document.createElement("a"),g=e.style,f=d.config,l=f.toolbarItemWidth,f=f.toolbarItemHeight;e.href="#"+c;e.title=a;e.highlighterId=b;e.commandName=c;e.innerHTML=a;if(isNaN(l)==!1)g.width=l+"px";if(isNaN(f)==!1)g.height=f+"px";e.onclick=function(a){try{d.toolbar.executeCommand(this,a||window.event,this.highlighterId,this.commandName)}catch(b){d.utils.alert(b.message)}return!1};return e},executeCommand:function(a,b,c,e,g){var c=d.vars.highlighters[c],f;return c==null||(f=c.toolbarCommands[e])==null?
null:f.execute(a,b,g)},items:{expandSource:function(a){this.create=function(){return a.getParam("collapse")!=!0?void 0:d.config.strings.expandSource};this.execute=function(b){var c=a.div;b.parentNode.removeChild(b);c.className=c.className.replace("collapsed","")}},viewSource:function(a){this.create=function(){return d.config.strings.viewSource};this.execute=function(){var b=d.utils.fixInputString(a.originalCode).replace(/</g,"&lt;"),c=d.utils.popup("","_blank",750,400,"location=0, resizable=1, menubar=0, scrollbars=1"),
b=d.utils.unindent(b);c.document.write("<pre>"+b+"</pre>");c.document.close()}},copyToClipboard:function(a){var b,c=a.id;this.create=function(){function a(b){var c="",e;for(e in b)c+="<param name='"+e+"' value='"+b[e]+"'/>";return c}function g(a){var b="",c;for(c in a)b+=" "+c+"='"+a[c]+"'";return b}var f=d.config;if(f.clipboardSwf==null)return null;var l={width:f.toolbarItemWidth,height:f.toolbarItemHeight,id:c+"_clipboard",type:"application/x-shockwave-flash",title:d.config.strings.copyToClipboard},
i={allowScriptAccess:"always",wmode:"transparent",flashVars:"highlighterId="+c,menu:"false"},f=f.clipboardSwf,l=/msie/i.test(navigator.userAgent)?"<object"+g({classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0"})+g(l)+">"+a(i)+a({movie:f})+"</object>":"<embed"+g(l)+g(i)+g({src:f})+"/>";b=document.createElement("div");b.innerHTML=l;return b};this.execute=function(b,c,f){switch(f.command){case "get":if(b=
d.utils.unindent(d.utils.fixInputString(a.originalCode).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")),window.clipboardData)window.clipboardData.setData("text",b);else return d.utils.unindent(b);case "ok":d.utils.alert(d.config.strings.copyToClipboardConfirmation);break;case "error":d.utils.alert(f.message)}}},printSource:function(a){this.create=function(){return d.config.strings.print};this.execute=function(){var b=document.createElement("IFRAME"),c=null;d.vars.printFrame!=null&&
document.body.removeChild(d.vars.printFrame);d.vars.printFrame=b;b.style.cssText="position:absolute;width:0px;height:0px;left:-500px;top:-500px;";document.body.appendChild(b);c=b.contentWindow.document;(function(a,b){for(var c=b.getElementsByTagName("link"),d=0;d<c.length;d++)c[d].rel.toLowerCase()=="stylesheet"&&/shCore\.css$/.test(c[d].href)&&a.write('<link type="text/css" rel="stylesheet" href="'+c[d].href+'"></link>')})(c,window.document);c.write('<div class="'+a.div.className.replace("collapsed",
"")+' printing">'+a.div.innerHTML+"</div>");c.close();b.contentWindow.focus();b.contentWindow.print()}},about:function(){this.create=function(){return d.config.strings.help};this.execute=function(){var a=d.utils.popup("","_blank",500,250,"scrollbars=0"),b=a.document;b.write(d.config.strings.aboutDialog);b.close();a.focus()}}}},utils:{indexOf:function(a,b,c){for(c=Math.max(c||0,0);c<a.length;c++)if(a[c]==b)return c;return-1},guid:function(a){return a+Math.round(Math.random()*1E6).toString()},merge:function(a,
b){var c={},e;for(e in a)c[e]=a[e];for(e in b)c[e]=b[e];return c},toBoolean:function(a){switch(a){case "true":return!0;case "false":return!1}return a},popup:function(a,b,c,e,d){d+=", left="+(screen.width-c)/2+", top="+(screen.height-e)/2+", width="+c+", height="+e;d=d.replace(/^,/,"");a=window.open(a,b,d);a.focus();return a},addEvent:function(a,b,c){a.attachEvent?(a["e"+b+c]=c,a[b+c]=function(){a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c])):a.addEventListener(b,c,!1)},alert:function(a){alert(d.config.strings.alert+
a)},findBrush:function(a,b){var c=d.vars.discoveredBrushes,e=null;if(c==null){var c={},g;for(g in d.brushes)if(e=d.brushes[g].aliases,e!=null){d.brushes[g].name=g.toLowerCase();for(var f=0;f<e.length;f++)c[e[f]]=g}d.vars.discoveredBrushes=c}e=d.brushes[c[a]];e==null&&b!=!1&&d.utils.alert(d.config.strings.noBrush+a);return e},eachLine:function(a,b){for(var c=a.split("\n"),e=0;e<c.length;e++)c[e]=b(c[e]);return c.join("\n")},trimFirstAndLastLines:function(a){return a.replace(/^[ ]*[\n]+|[\n]*[ ]*$/g,
"")},parseParams:function(a){for(var b,c={},e=new XRegExp("^\\[(?<values>(.*?))\\]$"),d=new XRegExp("(?<name>[\\w-]+)\\s*:\\s*(?<value>[\\w-%#]+|\\[.*?\\]|\".*?\"|'.*?')\\s*;?","g");(b=d.exec(a))!=null;){var f=b.value.replace(/^['"]|['"]$/g,"");f!=null&&e.test(f)&&(f=e.exec(f),f=f.values.length>0?f.values.split(/\s*,\s*/):[]);c[b.name]=f}return c},decorate:function(a,b){if(a==null||a.length==0||a=="\n")return a;a=a.replace(/</g,"&lt;");a=a.replace(/ {2,}/g,function(a){for(var b="",d=0;d<a.length-
1;d++)b+="&nbsp;";return b+" "});b!=null&&(a=d.utils.eachLine(a,function(a){if(a.length==0)return"";var e="",a=a.replace(/^(&nbsp;| )+/,function(a){e=a;return""});return a.length==0?e:e+'<code class="'+b+'">'+a+"</code>"}));return a},padNumber:function(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c},measureSpace:function(){var a=document.createElement("div"),b;b=0;var c=document.body;b=d.utils.guid("measureSpace");a.innerHTML='<div class="syntaxhighlighter"><div class="lines"><div class="line"><div class="content"><span class="block"><span id="'+
b+'">&nbsp;</span></span></div></div></div></div>';c.appendChild(a);b=document.getElementById(b);/opera/i.test(navigator.userAgent)?(b=window.getComputedStyle(b,null),b=parseInt(b.getPropertyValue("width"))):b=b.offsetWidth;c.removeChild(a);return b},processTabs:function(a,b){for(var c="",e=0;e<b;e++)c+=" ";return a.replace(/\t/g,c)},processSmartTabs:function(a,b){a.split("\n");for(var c="",e=0;e<50;e++)c+="                    ";return a=d.utils.eachLine(a,function(a){if(a.indexOf("\t")==-1)return a;
for(var e=0;(e=a.indexOf("\t"))!=-1;)a=a.substr(0,e)+c.substr(0,b-e%b)+a.substr(e+1,a.length);return a})},fixInputString:function(a){var b=/<br\s*\/?>|&lt;br\s*\/?&gt;/gi;d.config.bloggerMode==!0&&(a=a.replace(b,"\n"));d.config.stripBrs==!0&&(a=a.replace(b,""));return a},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},unindent:function(a){for(var b=d.utils.fixInputString(a).split("\n"),c=/^\s*/,e=1E3,g=0;g<b.length&&e>0;g++){var f=b[g];if(d.utils.trim(f).length!=0){f=c.exec(f);if(f==null)return a;
e=Math.min(f[0].length,e)}}if(e>0)for(g=0;g<b.length;g++)b[g]=b[g].substr(e);return b.join("\n")},matchesSortCallback:function(a,b){if(a.index<b.index)return-1;else if(a.index>b.index)return 1;else if(a.length<b.length)return-1;else if(a.length>b.length)return 1;return 0},getMatches:function(a,b){function c(a,b){return[new d.Match(a[0],a.index,b.css)]}for(var e=null,g=[],f=b.func?b.func:c;(e=b.regex.exec(a))!=null;)g=g.concat(f(e,b));return g},processUrls:function(a){return a.replace(d.regexLib.url,
function(a){var c="",e="";a.indexOf("&lt;")==0&&(e="&lt;",a=a.substring(4));a.indexOf("&gt;")==a.length-4&&(a=a.substring(0,a.length-4),c="&gt;");return e+'<a href="'+a+'">'+a+"</a>"+c})},getSyntaxHighlighterScriptTags:function(){for(var a=document.getElementsByTagName("script"),b=[],c=0;c<a.length;c++)a[c].type=="syntaxhighlighter"&&b.push(a[c]);return b},stripCData:function(a){var b=d.utils.trim(a),c=!1;b.indexOf("<![CDATA[")==0&&(b=b.substring(9),c=!0);b.indexOf("]]\>")==b.length-3&&(b=b.substring(0,
b.length-3),c=!0);return c?b:a}},highlight:function(a,b){function c(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b}var e=b?[b]:c(document.getElementsByTagName(d.config.tagName)),g=null,f=d.config;f.useScriptTags&&(e=e.concat(d.utils.getSyntaxHighlighterScriptTags()));if(e.length!==0)for(var l=0;l<e.length;l++){var i=e[l],j=d.utils.parseParams(i.className),k,m,j=d.utils.merge(a,j);k=j.brush;if(k!=null){if(j["html-script"]=="true"||d.defaults["html-script"]==!0)g=new d.HtmlScript(k),k="htmlscript";
else if(g=d.utils.findBrush(k))k=g.name,g=new g;else continue;m=i.innerHTML;f.useScriptTags&&(m=d.utils.stripCData(m));j["brush-name"]=k;g.highlight(m,j);j=g.div;if(d.config.debug)j=document.createElement("textarea"),j.value=g.div.innerHTML,j.style.width="70em",j.style.height="30em";i.parentNode.replaceChild(j,i)}}},all:function(a){d.utils.addEvent(window,"load",function(){d.highlight(a)})},Match:function(a,b,c){this.value=a;this.index=b;this.length=a.length;this.css=c;this.brushName=null}};d.Match.prototype.toString=
function(){return this.value};d.HtmlScript=function(a){function b(a,b){for(var c=0;c<a.length;c++)a[c].index+=b}var c=d.utils.findBrush(a),e,g=new d.brushes.Xml;if(c!=null)e=new c,this.xmlBrush=g,e.htmlScript==null?d.utils.alert(d.config.strings.brushNotHtmlScript+a):g.regexList.push({regex:e.htmlScript.code,func:function(a){for(var g=a.code,i=[],j=e.regexList,k=a.index+a.left.length,m=e.htmlScript,h,n=0;n<j.length;n++)h=d.utils.getMatches(g,j[n]),b(h,k),i=i.concat(h);m.left!=null&&a.left!=null&&
(h=d.utils.getMatches(a.left,m.left),b(h,a.index),i=i.concat(h));m.right!=null&&a.right!=null&&(h=d.utils.getMatches(a.right,m.right),b(h,a.index+a[0].lastIndexOf(a.right)),i=i.concat(h));for(a=0;a<i.length;a++)i[a].brushName=c.name;return i}})};d.HtmlScript.prototype.highlight=function(a,b){this.xmlBrush.highlight(a,b);this.div=this.xmlBrush.div};d.Highlighter=function(){};d.Highlighter.prototype={getParam:function(a,b){var c=this.params[a];return d.utils.toBoolean(c==null?b:c)},create:function(a){return document.createElement(a)},
findMatches:function(a,b){var c=[];if(a!=null)for(var e=0;e<a.length;e++)typeof a[e]=="object"&&(c=c.concat(d.utils.getMatches(b,a[e])));return c.sort(d.utils.matchesSortCallback)},removeNestedMatches:function(){for(var a=this.matches,b=0;b<a.length;b++)if(a[b]!==null)for(var c=a[b],e=c.index+c.length,d=b+1;d<a.length&&a[b]!==null;d++){var f=a[d];if(f!==null)if(f.index>e)break;else f.index==c.index&&f.length>c.length?this.matches[b]=null:f.index>=c.index&&f.index<e&&(this.matches[d]=null)}},createDisplayLines:function(a){var b=
a.split("\n"),c=parseInt(this.getParam("first-line")),e=this.getParam("pad-line-numbers"),g=this.getParam("highlight",[]),f=this.getParam("gutter"),a="";e==!0?e=(c+b.length-1).toString().length:isNaN(e)==!0&&(e=0);for(var l=0;l<b.length;l++){var i=b[l],j=/^(&nbsp;|\s)+/.exec(i),k="alt"+(l%2==0?1:2),m=d.utils.padNumber(c+l,e),h=d.utils.indexOf(g,(c+l).toString())!=-1,n=null;j!=null&&(n=j[0].toString(),i=i.substr(n.length));i=d.utils.trim(i);i.length==0&&(i="&nbsp;");h&&(k+=" highlighted");a+='<div class="line '+
k+'"><table><tr>'+(f?'<td class="number"><code>'+m+"</code></td>":"")+'<td class="content">'+(n!=null?'<code class="spaces">'+n.replace(" ","&nbsp;")+"</code>":"")+i+"</td></tr></table></div>"}return a},processMatches:function(a,b){function c(a){return(a=a?a.brushName||l:l)?a+" ":""}for(var e=0,g="",f=d.utils.decorate,l=this.getParam("brush-name",""),i=0;i<b.length;i++){var j=b[i],k;j===null||j.length===0||(k=c(j),g+=f(a.substr(e,j.index-e),k+"plain")+f(j.value,k+j.css),e=j.index+j.length)}g+=f(a.substr(e),
c()+"plain");return g},highlight:function(a,b){var c=d.vars,e;this.params={};this.bar=this.code=this.lines=this.div=null;this.toolbarCommands={};this.id=d.utils.guid("highlighter_");c.highlighters[this.id]=this;a===null&&(a="");this.params=d.utils.merge(d.defaults,b||{});if(this.getParam("light")==!0)this.params.toolbar=this.params.gutter=!1;this.div=c=this.create("DIV");this.lines=this.create("DIV");this.lines.className="lines";className="syntaxhighlighter";c.id=this.id;this.getParam("collapse")&&
(className+=" collapsed");this.getParam("gutter")==!1&&(className+=" nogutter");this.getParam("wrap-lines")==!1&&(this.lines.className+=" no-wrap");className+=" "+this.getParam("class-name");className+=" "+this.getParam("brush-name");c.className=className;this.originalCode=a;this.code=d.utils.trimFirstAndLastLines(a).replace(/\r/g," ");e=this.getParam("tab-size");this.code=this.getParam("smart-tabs")==!0?d.utils.processSmartTabs(this.code,e):d.utils.processTabs(this.code,e);this.code=d.utils.unindent(this.code);
if(this.getParam("toolbar")){this.bar=this.create("DIV");this.bar.className="bar";this.bar.appendChild(d.toolbar.create(this));c.appendChild(this.bar);var g=this.bar,f=function(){g.className=g.className.replace("show","")};c.onmouseover=function(){f();g.className+=" show"};c.onmouseout=function(){f()}}c.appendChild(this.lines);this.matches=this.findMatches(this.regexList,this.code);this.removeNestedMatches();a=this.processMatches(this.code,this.matches);a=this.createDisplayLines(d.utils.trim(a));
this.getParam("auto-links")&&(a=d.utils.processUrls(a));this.lines.innerHTML=a},getKeywords:function(a){a=a.replace(/^\s+|\s+$/g,"").replace(/\s+/g,"|");return"\\b(?:"+a+")\\b"},forHtmlScript:function(a){this.htmlScript={left:{regex:a.left,css:"script"},right:{regex:a.right,css:"script"},code:new XRegExp("(?<left>"+a.left.source+")(?<code>.*?)(?<right>"+a.right.source+")","sgi")}}};return d}();
window.XRegExp||function(){var d={exec:RegExp.prototype.exec,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},a={part:/(?:[^\\([#\s.]+|\\(?!k<[\w$]+>|[pP]{[^}]+})[\S\s]?|\((?=\?(?!#|<[\w$]+>)))+|(\()(?:\?(?:(#)[^)]*\)|<([$\w]+)>))?|\\(?:k<([\w$]+)>|[pP]{([^}]+)})|(\[\^?)|([\S\s])/g,replaceVar:/(?:[^$]+|\$(?![1-9$&`']|{[$\w]+}))+|\$(?:([1-9]\d*|[$&`'])|{([$\w]+)})/g,extended:/^(?:\s+|#.*)+/,quantifier:/^(?:[?*+]|{\d+(?:,\d*)?})/,classLeft:/&&\[\^?/g,classRight:/]/g},
b=/()??/.exec("")[1]!==void 0,c={};XRegExp=function(b,g){if(b instanceof RegExp){if(g!==void 0)throw TypeError("can't supply flags when constructing one RegExp from another");return b.addFlags()}var g=g||"",f=g.indexOf("s")>-1,l=g.indexOf("x")>-1,i=!1,j=[],k=[],m=a.part,h,n;for(m.lastIndex=0;h=d.exec.call(m,b);)if(h[2])a.quantifier.test(b.slice(m.lastIndex))||k.push("(?:)");else if(h[1])j.push(h[3]||null),h[3]&&(i=!0),k.push("(");else if(h[4]){a:{for(n=0;n<j.length;n++)if(j[n]===h[4])break a;n=-1}k.push(n>
-1?"\\"+(n+1)+(isNaN(b.charAt(m.lastIndex))?"":"(?:)"):h[0])}else h[5]?k.push(c.unicode?c.unicode.get(h[5],h[0].charAt(1)==="P"):h[0]):h[6]?b.charAt(m.lastIndex)==="]"?(k.push(h[6]==="["?"(?!)":"[\\S\\s]"),m.lastIndex++):(n=XRegExp.matchRecursive("&&"+b.slice(h.index),a.classLeft,a.classRight,"",{escapeChar:"\\"})[0],k.push(h[6]+n+"]"),m.lastIndex+=n.length+1):h[7]?f&&h[7]==="."?k.push("[\\S\\s]"):l&&a.extended.test(h[7])?(h=d.exec.call(a.extended,b.slice(m.lastIndex-1))[0].length,a.quantifier.test(b.slice(m.lastIndex-
1+h))||k.push("(?:)"),m.lastIndex+=h-1):k.push(h[7]):k.push(h[0]);f=RegExp(k.join(""),d.replace.call(g,/[sx]+/g,""));f._x={source:b,captureNames:i?j:null};return f};XRegExp.addPlugin=function(a,b){c[a]=b};RegExp.prototype.exec=function(a){var c=d.exec.call(this,a),f;if(c){b&&c.length>1&&(a=RegExp("^"+this.source+"$(?!\\s)",this.getNativeFlags()),d.replace.call(c[0],a,function(){for(f=1;f<arguments.length-2;f++)arguments[f]===void 0&&(c[f]=void 0)}));if(this._x&&this._x.captureNames)for(f=1;f<c.length;f++)(a=
this._x.captureNames[f-1])&&(c[a]=c[f]);this.global&&this.lastIndex>c.index+c[0].length&&this.lastIndex--}return c}}();RegExp.prototype.getNativeFlags=function(){return(this.global?"g":"")+(this.ignoreCase?"i":"")+(this.multiline?"m":"")+(this.extended?"x":"")+(this.sticky?"y":"")};RegExp.prototype.addFlags=function(d){d=new XRegExp(this.source,(d||"")+this.getNativeFlags());if(this._x)d._x={source:this._x.source,captureNames:this._x.captureNames?this._x.captureNames.slice(0):null};return d};
RegExp.prototype.call=function(d,a){return this.exec(a)};RegExp.prototype.apply=function(d,a){return this.exec(a[0])};XRegExp.cache=function(d,a){var b="/"+d+"/"+(a||"");return XRegExp.cache[b]||(XRegExp.cache[b]=new XRegExp(d,a))};XRegExp.escape=function(d){return d.replace(/[-[\]{}()*+?.\\^$|,#\s]/g,"\\$&")};
XRegExp.matchRecursive=function(d,a,b,c,e){var e=e||{},g=e.escapeChar,e=e.valueNames,c=c||"",f=c.indexOf("g")>-1,l=c.indexOf("i")>-1,i=c.indexOf("m")>-1,j=c.indexOf("y")>-1,c=c.replace(/y/g,""),a=a instanceof RegExp?a.global?a:a.addFlags("g"):new XRegExp(a,"g"+c),b=b instanceof RegExp?b.global?b:b.addFlags("g"):new XRegExp(b,"g"+c),c=[],k=0,m=0,h=0,n=0,o,p,q;if(g){if(g.length>1)throw SyntaxError("can't supply more than one escape character");if(i)throw TypeError("can't supply escape character when using the multiline flag");
q=XRegExp.escape(g);q=RegExp("^(?:"+q+"[\\S\\s]|(?:(?!"+a.source+"|"+b.source+")[^"+q+"])+)+",l?"i":"")}for(;;){a.lastIndex=b.lastIndex=h+(g?(q.exec(d.slice(h))||[""])[0].length:0);l=a.exec(d);i=b.exec(d);l&&i&&(l.index<=i.index?i=null:l=null);if(l||i)m=(l||i).index,h=(l?a:b).lastIndex;else if(!k)break;if(j&&!k&&m>n)break;if(l)k++||(o=m,p=h);else if(i&&k){if(!--k&&(e?(e[0]&&o>n&&c.push([e[0],d.slice(n,o),n,o]),e[1]&&c.push([e[1],d.slice(o,p),o,p]),e[2]&&c.push([e[2],d.slice(p,m),p,m]),e[3]&&c.push([e[3],
d.slice(m,h),m,h])):c.push(d.slice(p,m)),n=h,!f))break}else throw a.lastIndex=b.lastIndex=0,Error("subject data contains unbalanced delimiters");m===h&&h++}f&&!j&&e&&e[0]&&d.length>n&&c.push([e[0],d.slice(n),n,d.length]);a.lastIndex=b.lastIndex=0;return c};
