(function(b,c,a){b.beautyOfCode={settings:{autoLoad:!0,baseUrl:"http://alexgorbatchev.com.s3.amazonaws.com/pub/sh/2.1.382/",scripts:"scripts/",styles:"styles/",theme:"Default",brushes:["Plain"],target:".sh",config:{debug:!1},defaults:{},ready:function(){b.beautyOfCode.beautifyAll()}},init:function(h){h=b.extend({},b.beautyOfCode.settings,h);h.config.clipboardSwf||(h.config.clipboardSwf=h.baseUrl+h.scripts+"clipboard.swf");b(a).ready(function(){if(h.autoLoad){b.beautyOfCode.utils.loadCss(h.baseUrl+
h.styles+"shCore.css");b.beautyOfCode.utils.loadCss(h.baseUrl+h.styles+"shTheme"+h.theme+".css","shTheme");var a=[];!0==h.debug?a.push(h.baseUrl+"src/shCore.js"):a.push(h.baseUrl+h.scripts+"shCore.js");b.each(h.brushes,function(b,c){a.push(h.baseUrl+h.scripts+"shBrush"+c+".js")});b.beautyOfCode.utils.loadAllScripts(a,function(){h&&h.config&&b.extend(SyntaxHighlighter.config,h.config);h&&h.defaults&&b.extend(SyntaxHighlighter.defaults,h.defaults);h.ready()})}else h.ready()})},beautifyAll:function(a){a=
b.extend({},b.beautyOfCode.settings,a);var l=this;b(a.target).each(function(){var c=b(this);l.dom_cache.push(c);c=l.utils.getBrush(c.data().brush);-1===b.inArray(c,a.brushes)&&a.brushes.push(c)});a.ready=function(){for(var b=0;b<=l.dom_cache.length-1;b++){var a=l.dom_cache[b];a.beautifyCode(a.data().brush)}};b.beautyOfCode.init(a)},dom_cache:[],utils:{loaded:[],loadScript:function(a,l){var c=this;-1===b.inArray(a,this.loaded)?b.ajax({url:a,complete:function(){l();c.loaded.push(a)},type:"GET",dataType:"script",
cache:!0}):l()},loadAllScripts:function(a,l,c){a&&0!=a.length?b.beautyOfCode.utils.loadScript(a[0],function(){b.beautyOfCode.utils.loadAllScripts(a.slice(1,a.length),l)}):l()},loadCss:function(h,c){var s=b("head")[0];if(h&&s){var n=a.createElement("link");n.setAttribute("rel","stylesheet");n.setAttribute("href",h);c&&(n.id=c);s.appendChild(n)}},addCss:function(h,c){var s=b("head")[0];if(h&&s){var n=a.createElement("style");n.setAttribute("type","text/css");c&&(n.id=c);n.styleSheet?n.styleSheet.cssText=
h:b(n).text(h);s.appendChild(n)}},addCssForBrush:function(a,c){a.isCssInitialized||(b.beautyOfCode.utils.addCss(c.Style),a.isCssInitialized=!0)},getBrush:function(b){var a={AppleScript:["applescript"],AS3:["actionscript3","as3","as"],Bash:["bash","shell"],ColdFusion:["coldfusion","cf"],Cpp:["cpp","c","h","hpp"],CSharp:["c#","c-sharp","csharp","cs"],Css:["css"],Delphi:["delphi","pascal","pas"],Diff:["diff","patch"],Erlang:["erl","erlang"],Groovy:["groovy"],Java:["java"],JavaFX:["jfx","javafx"],JScript:["js",
"jscript","javascript","json"],Perl:["perl","pl"],Php:["php"],Plain:["text","plain"],Python:["py","python"],Ruby:["ruby","rails","ror","rb"],Sass:["sass","scss"],Scala:["scala"],Sql:["sql"],Vb:["vb","vbnet"],Xml:["xml","xhtml","xslt","html"]},c;for(c in a)for(var n=0;n<=a[c].length-1;n++)if(a[c][n]==b)return c;return"Plain"}}};b.fn.beautifyCode=function(a,c){this.each(function(a,h){var w=b(h),r=w.data(),B={"class-name":r.className,"first-line":r.firstLine,"tab-size":r.tabSize,"smart-tabs":r.smartTabs,
ruler:r.ruler,gutter:r.gutter,highlight:r.highlight,toolbar:r.toolbar,collapse:r.collapse,"auto-links":r.autoLinks,light:r.light,"wrap-lines":r.warpLines,"html-script":r.htmlScript},r=r.brush?r.brush:"plain",k=w.text();b.browser.msie&&9<b.browser.version&&(k=k.replace(/\x0D\x0A|\x0D|\x0A/g,"\n\r"));B=b.extend({},SyntaxHighlighter.defaults,c,B);if(!0==B["html-script"])highlighter=new SyntaxHighlighter.HtmlScript(r);else if(r=SyntaxHighlighter.utils.findBrush(r))highlighter=new r;else return;b.beautyOfCode.utils.addCssForBrush(r,
highlighter);highlighter.highlight(k,B);highlighter.source=h;w.replaceWith(highlighter.div)})}})(jQuery,this,this.document);
(function(b){b._i18n={trans:{},"default":"en",language:"en"};b.i18n=function(){if(2>arguments.length)return b._i18n.language=arguments[0],b._i18n.language;if("string"==typeof arguments[1]){var c;c=arguments[0];var a=arguments[1],h=!1;b._i18n.trans[b._i18n.language]&&b._i18n.trans[b._i18n.language][c]&&b._i18n.trans[b._i18n.language][c][a]?h=b._i18n.trans[b._i18n.language][c][a]:b._i18n.trans[b._i18n["default"]]&&b._i18n.trans[b._i18n["default"]][c]&&b._i18n.trans[b._i18n["default"]][c][a]&&(h=b._i18n.trans[b._i18n["default"]][c][a]);
c=h||a;return arguments[2]&&"object"==typeof arguments[2]?b.format(c,arguments[2]):c}a=arguments[0].split(".");c=a[0];a=a[1]||"jQuery";b._i18n.trans[c]||(b._i18n.trans[c]={});b._i18n.trans[c][a]?b.extend(b._i18n.trans[c][a],arguments[1]):b._i18n.trans[c][a]=arguments[1]}})(jQuery);
!function(b){b.extend({tablesorter:new function(){function a(){var d=arguments[0],e=1<arguments.length?Array.prototype.slice.call(arguments):d;if("undefined"!==typeof console&&"undefined"!==typeof console.log)console[/error/i.test(d)?"error":/warn/i.test(d)?"warn":"log"](e);else alert(e)}function h(d,e){a(d+" ("+((new Date).getTime()-e.getTime())+"ms)")}function c(d){for(var e in d)return!1;return!0}function s(d,e,f){if(!e)return"";var z=d.config,m=z.textExtraction,a="",a="simple"===m?z.supportsTextContent?
e.textContent:b(e).text():"function"===typeof m?m(e,d,f):"object"===typeof m&&m.hasOwnProperty(f)?m[f](e,d,f):z.supportsTextContent?e.textContent:b(e).text();return b.trim(a)}function n(d){var e=d.config,f=e.$tbodies=e.$table.children("tbody:not(."+e.cssInfoBlock+")"),b,m,x,p,c,q,t,k="";if(0===f.length)return e.debug?a("Warning: *Empty table!* Not building a parser cache"):"";e.debug&&(t=new Date,a("Detecting parsers for each column"));f=f[0].rows;if(f[0])for(b=[],m=f[0].cells.length,x=0;x<m;x++){p=
e.$headers.filter(":not([colspan])");p=p.add(e.$headers.filter('[colspan="1"]')).filter('[data-column="'+x+'"]:last');c=e.headers[x];q=g.getParserById(g.getData(p,c,"sorter"));e.empties[x]=g.getData(p,c,"empty")||e.emptyTo||(e.emptyToBottom?"bottom":"top");e.strings[x]=g.getData(p,c,"string")||e.stringTo||"max";if(!q)a:{p=d;c=f;q=-1;for(var l=x,n=void 0,v=g.parsers.length,u=!1,r="",n=!0;""===r&&n;)q++,c[q]?(u=c[q].cells[l],r=s(p,u,l),p.config.debug&&a("Checking if value was empty on row "+q+", column: "+
l+': "'+r+'"')):n=!1;for(;0<=--v;)if((n=g.parsers[v])&&"text"!==n.id&&n.is&&n.is(r,p,u)){q=n;break a}q=g.getParserById("text")}e.debug&&(k+="column:"+x+"; parser:"+q.id+"; string:"+e.strings[x]+"; empty: "+e.empties[x]+"\n");b.push(q)}e.debug&&(a(k),h("Completed detecting parsers",t));e.parsers=b}function w(d){var e=d.tBodies,f=d.config,z,m,x=f.parsers,p,c,q,t,k,l,n,v=[];f.cache={};if(!x)return f.debug?a("Warning: *Empty table!* Not building a cache"):"";f.debug&&(n=new Date);f.showProcessing&&g.isProcessing(d,
!0);for(t=0;t<e.length;t++)if(f.cache[t]={row:[],normalized:[]},!b(e[t]).hasClass(f.cssInfoBlock)){z=e[t]&&e[t].rows.length||0;m=e[t].rows[0]&&e[t].rows[0].cells.length||0;for(c=0;c<z;++c)if(k=b(e[t].rows[c]),l=[],k.hasClass(f.cssChildRow)&&0!==c)f.cache[t].row[f.cache[t].row.length-1]=f.cache[t].row[f.cache[t].row.length-1].add(k),k.prev().hasClass(f.cssChildRow)||k.prev().addClass(g.css.cssHasChild);else{f.cache[t].row.push(k);for(q=0;q<m;++q)"undefined"===typeof x[q]?f.debug&&a("No parser found for cell:",
k[0].cells[q],"does it have a header?"):(p=s(d,k[0].cells[q],q),p=x[q].format(p,d,k[0].cells[q],q),l.push(p),"numeric"===(x[q].type||"").toLowerCase()&&(v[q]=Math.max(Math.abs(p)||0,v[q]||0)));l.push(f.cache[t].normalized.length);f.cache[t].normalized.push(l)}f.cache[t].colMax=v}f.showProcessing&&g.isProcessing(d);f.debug&&h("Building cache for "+z+" rows",n)}function r(d,e){var f=d.config,z=f.widgetOptions,m=d.tBodies,a=[],p=f.cache,k,q,t,n,v,r,s,u,A,y,C;if(c(p))return f.appender?f.appender(d,a):
d.isUpdating?f.$table.trigger("updateComplete",d):"";f.debug&&(C=new Date);for(u=0;u<m.length;u++)if(k=b(m[u]),k.length&&!k.hasClass(f.cssInfoBlock)){v=g.processTbody(d,k,!0);k=p[u].row;q=p[u].normalized;n=(t=q.length)?q[0].length-1:0;for(r=0;r<t;r++)if(y=q[r][n],a.push(k[y]),!f.appender||f.pager&&!(f.pager.removeRows&&z.pager_removeRows||f.pager.ajax))for(A=k[y].length,s=0;s<A;s++)v.append(k[y][s]);g.processTbody(d,v,!1)}f.appender&&f.appender(d,a);f.debug&&h("Rebuilt table",C);e||f.appender||g.applyWidget(d);
d.isUpdating&&f.$table.trigger("updateComplete",d)}function B(d){var e=[],f=0,z=b(d).children("thead, tfoot").children("tr"),m,a,g,c,k,h,l,n,v,r;for(m=0;m<z.length;m++)for(k=z[m].cells,a=0;a<k.length;a++){c=k[a];h=c.parentNode.rowIndex;b(c).index();l=c.rowSpan||1;n=c.colSpan||1;"undefined"===typeof e[h]&&(e[h]=[]);for(g=0;g<e[h].length+1;g++)if("undefined"===typeof e[h][g]){v=g;break}f=Math.max(v,f);b(c).attr({"data-column":v});for(g=h;g<h+l;g++)for("undefined"===typeof e[g]&&(e[g]=[]),r=e[g],c=v;c<
v+n;c++)r[c]="x"}d.config.columns=f+1}function k(d){return/^d/i.test(d)||1===d}function A(d){var e,f,z,m,x,c,l,q=d.config;q.headerList=[];q.headerContent=[];q.debug&&(l=new Date);B(d);m=q.cssIcon?'<i class="'+(q.cssIcon===g.css.icon?g.css.icon:q.cssIcon+" "+g.css.icon)+'"></i>':"";q.$headers=b(d).find(q.selectorHeaders).each(function(d){f=b(this);e=q.headers[d];q.headerContent[d]=b(this).html();x=q.headerTemplate.replace(/\{content\}/g,b(this).html()).replace(/\{icon\}/g,m);q.onRenderTemplate&&(z=
q.onRenderTemplate.apply(f,[d,x]))&&"string"===typeof z&&(x=z);b(this).html('<div class="'+g.css.headerIn+'">'+x+"</div>");q.onRenderHeader&&q.onRenderHeader.apply(f,[d]);this.column=parseInt(b(this).attr("data-column"),10);this.order=k(g.getData(f,e,"sortInitialOrder")||q.sortInitialOrder)?[1,0,2]:[0,1,2];this.count=-1;this.lockedOrder=!1;c=g.getData(f,e,"lockedOrder")||!1;"undefined"!==typeof c&&!1!==c&&(this.order=this.lockedOrder=k(c)?[1,1,1]:[0,0,0]);f.addClass(g.css.header+" "+q.cssHeader);
q.headerList[d]=this;f.parent().addClass(g.css.headerRow+" "+q.cssHeaderRow).attr("role","row");q.tabIndex&&f.attr("tabindex",0)}).attr({scope:"col",role:"columnheader"});v(d);q.debug&&(h("Built headers:",l),a(q.$headers))}function y(d,e,f){var b=d.config;b.$table.find(b.selectorRemove).remove();n(d);w(d);D(b.$table,e,f)}function v(d){var e,f,z=d.config;z.$headers.each(function(m,a){f=b(a);e="false"===g.getData(a,z.headers[m],"sorter");a.sortDisabled=e;f[e?"addClass":"removeClass"]("sorter-false").attr("aria-disabled",
""+e);d.id&&(e?f.removeAttr("aria-controls"):f.attr("aria-controls",d.id))})}function C(d){var e,f,a,m=d.config,c=m.sortList,p=g.css.sortNone+" "+m.cssNone,h=[g.css.sortAsc+" "+m.cssAsc,g.css.sortDesc+" "+m.cssDesc],k=["ascending","descending"],t=b(d).find("tfoot tr").children().removeClass(h.join(" "));m.$headers.removeClass(h.join(" ")).addClass(p).attr("aria-sort","none");a=c.length;for(e=0;e<a;e++)if(2!==c[e][1]&&(d=m.$headers.not(".sorter-false").filter('[data-column="'+c[e][0]+'"]'+(1===a?":last":
"")),d.length))for(f=0;f<d.length;f++)d[f].sortDisabled||(d.eq(f).removeClass(p).addClass(h[c[e][1]]).attr("aria-sort",k[c[e][1]]),t.length&&t.filter('[data-column="'+c[e][0]+'"]').eq(f).addClass(h[c[e][1]]));m.$headers.not(".sorter-false").each(function(){var d=b(this),e=this.order[(this.count+1)%(m.sortReset?3:2)],e=d.text()+": "+g.language[d.hasClass(g.css.sortAsc)?"sortAsc":d.hasClass(g.css.sortDesc)?"sortDesc":"sortNone"]+g.language[0===e?"nextAsc":1===e?"nextDesc":"nextNone"];d.attr("aria-label",
e)})}function E(d){if(d.config.widthFixed&&0===b(d).find("colgroup").length){var e=b("<colgroup>"),f=b(d).width();b(d.tBodies[0]).find("tr:first").children("td:visible").each(function(){e.append(b("<col>").css("width",parseInt(b(this).width()/f*1E3,10)/10+"%"))});b(d).prepend(e)}}function I(d,e){var f,a,m,g=d.config,c=e||g.sortList;g.sortList=[];b.each(c,function(d,e){f=[parseInt(e[0],10),parseInt(e[1],10)];if(m=g.$headers[f[0]])g.sortList.push(f),a=b.inArray(f[1],m.order),m.count=0<=a?a:f[1]%(g.sortReset?
3:2)})}function J(d,e){return d&&d[e]?d[e].type||"":""}function K(d,e,f){var a,m,c,p=d.config,h=!f[p.sortMultiSortKey],k=p.$table;k.trigger("sortStart",d);e.count=f[p.sortResetKey]?2:(e.count+1)%(p.sortReset?3:2);p.sortRestart&&(m=e,p.$headers.each(function(){this===m||!h&&b(this).is("."+g.css.sortDesc+",."+g.css.sortAsc)||(this.count=-1)}));m=e.column;if(h){p.sortList=[];if(null!==p.sortForce)for(a=p.sortForce,f=0;f<a.length;f++)a[f][0]!==m&&p.sortList.push(a[f]);a=e.order[e.count];if(2>a&&(p.sortList.push([m,
a]),1<e.colSpan))for(f=1;f<e.colSpan;f++)p.sortList.push([m+f,a])}else{if(p.sortAppend&&1<p.sortList.length)for(f=0;f<p.sortAppend.length;f++)c=g.isValueInArray(p.sortAppend[f][0],p.sortList),0<=c&&p.sortList.splice(c,1);if(0<=g.isValueInArray(m,p.sortList))for(f=0;f<p.sortList.length;f++)c=p.sortList[f],a=p.$headers[c[0]],c[0]===m&&(c[1]=a.order[e.count],2===c[1]&&(p.sortList.splice(f,1),a.count=-1));else if(a=e.order[e.count],2>a&&(p.sortList.push([m,a]),1<e.colSpan))for(f=1;f<e.colSpan;f++)p.sortList.push([m+
f,a])}if(null!==p.sortAppend)for(a=p.sortAppend,f=0;f<a.length;f++)a[f][0]!==m&&p.sortList.push(a[f]);k.trigger("sortBegin",d);setTimeout(function(){C(d);F(d);r(d);k.trigger("sortEnd",d)},1)}function F(d){var e,f,b,a,k,p,n,q,t,v,r,s,y=0,u=d.config,A=u.textSorter||"",C=u.sortList,w=C.length,E=d.tBodies.length;if(!u.serverSideSorting&&!c(u.cache)){u.debug&&(t=new Date);for(f=0;f<E;f++)k=u.cache[f].colMax,q=(p=u.cache[f].normalized)&&p[0]?p[0].length-1:0,p.sort(function(f,c){for(e=0;e<w;e++){a=C[e][0];
n=C[e][1];y=0===n;if(u.sortStable&&f[a]===c[a]&&1===w)break;(b=/n/i.test(J(u.parsers,a)))&&u.strings[a]?(b="boolean"===typeof u.string[u.strings[a]]?(y?1:-1)*(u.string[u.strings[a]]?-1:1):u.strings[a]?u.string[u.strings[a]]||0:0,v=u.numberSorter?u.numberSorter(f[a],c[a],y,k[a],d):g["sortNumeric"+(y?"Asc":"Desc")](f[a],c[a],b,k[a],a,d)):(r=y?f:c,s=y?c:f,v="function"===typeof A?A(r[a],s[a],y,a,d):"object"===typeof A&&A.hasOwnProperty(a)?A[a](r[a],s[a],y,a,d):g["sortNatural"+(y?"Asc":"Desc")](f[a],c[a],
a,d,u));if(v)return v}return f[q]-c[q]});u.debug&&h("Sorting on "+C.toString()+" and dir "+n+" time",t)}}function G(d,e){d[0].isUpdating&&d.trigger("updateComplete");"function"===typeof e&&e(d[0])}function D(d,e,f){var b=d[0].config.sortList;!1!==e&&!d[0].isProcessing&&b.length?d.trigger("sorton",[b,function(){G(d,f)},!0]):(d.trigger("applyWidgets"),G(d,f))}function H(d){var e=d.config,f=e.$table;f.unbind("sortReset update updateRows updateCell updateAll addRows updateComplete sorton appendCache updateCache applyWidgetId applyWidgets refreshWidgets destroy mouseup mouseleave ".split(" ").join(e.namespace+
" ")).bind("sortReset"+e.namespace,function(f){f.stopPropagation();e.sortList=[];C(d);F(d);r(d)}).bind("updateAll"+e.namespace,function(f,b,a){f.stopPropagation();d.isUpdating=!0;g.refreshWidgets(d,!0,!0);g.restoreHeaders(d);A(d);g.bindEvents(d,e.$headers);H(d);y(d,b,a)}).bind("update"+e.namespace+" updateRows"+e.namespace,function(e,f,b){e.stopPropagation();d.isUpdating=!0;v(d);y(d,f,b)}).bind("updateCell"+e.namespace,function(a,m,g,c){a.stopPropagation();d.isUpdating=!0;f.find(e.selectorRemove).remove();
var k,h,t;k=f.find("tbody");a=k.index(b(m).parents("tbody").filter(":first"));var l=b(m).parents("tr").filter(":first");m=b(m)[0];k.length&&0<=a&&(h=k.eq(a).find("tr").index(l),t=b(m).index(),k=e.cache[a].normalized[h].length-1,e.cache[a].row[e.cache[a].normalized[h][k]]=l,e.cache[a].normalized[h][t]=e.parsers[t].format(s(d,m,t),d,m,t),D(f,g,c))}).bind("addRows"+e.namespace,function(b,a,g,k){b.stopPropagation();d.isUpdating=!0;if(c(e.cache))v(d),y(d,g,k);else{var h,q=a.filter("tr").length,t=[],r=
a[0].cells.length,A=f.find("tbody").index(a.parents("tbody").filter(":first"));e.parsers||n(d);for(b=0;b<q;b++){for(h=0;h<r;h++)t[h]=e.parsers[h].format(s(d,a[b].cells[h],h),d,a[b].cells[h],h);t.push(e.cache[A].row.length);e.cache[A].row.push([a[b]]);e.cache[A].normalized.push(t);t=[]}D(f,g,k)}}).bind("updateComplete"+e.namespace,function(){d.isUpdating=!1}).bind("sorton"+e.namespace,function(e,b,a,g){var h=d.config;e.stopPropagation();f.trigger("sortStart",this);I(d,b);C(d);h.delayInit&&c(h.cache)&&
w(d);f.trigger("sortBegin",this);F(d);r(d,g);f.trigger("sortEnd",this).trigger("applyWidgets");"function"===typeof a&&a(d)}).bind("appendCache"+e.namespace,function(e,b,a){e.stopPropagation();r(d,a);"function"===typeof b&&b(d)}).bind("updateCache"+e.namespace,function(b,a){e.parsers||n(d);w(d);"function"===typeof a&&a(d)}).bind("applyWidgetId"+e.namespace,function(b,a){b.stopPropagation();g.getWidgetById(a).format(d,e,e.widgetOptions)}).bind("applyWidgets"+e.namespace,function(e,b){e.stopPropagation();
g.applyWidget(d,b)}).bind("refreshWidgets"+e.namespace,function(e,b,a){e.stopPropagation();g.refreshWidgets(d,b,a)}).bind("destroy"+e.namespace,function(e,b,a){e.stopPropagation();g.destroy(d,b,a)})}var g=this;g.version="2.15.13";g.parsers=[];g.widgets=[];g.defaults={theme:"default",widthFixed:!1,showProcessing:!1,headerTemplate:"{content}",onRenderTemplate:null,onRenderHeader:null,cancelSelection:!0,tabIndex:!0,dateFormat:"mmddyyyy",sortMultiSortKey:"shiftKey",sortResetKey:"ctrlKey",usNumberFormat:!0,
delayInit:!1,serverSideSorting:!1,headers:{},ignoreCase:!0,sortForce:null,sortList:[],sortAppend:null,sortStable:!1,sortInitialOrder:"asc",sortLocaleCompare:!1,sortReset:!1,sortRestart:!1,emptyTo:"bottom",stringTo:"max",textExtraction:"simple",textSorter:null,numberSorter:null,widgets:[],widgetOptions:{zebra:["even","odd"]},initWidgets:!0,initialized:null,tableClass:"",cssAsc:"",cssDesc:"",cssNone:"",cssHeader:"",cssHeaderRow:"",cssProcessing:"",cssChildRow:"tablesorter-childRow",cssIcon:"tablesorter-icon",
cssInfoBlock:"tablesorter-infoOnly",selectorHeaders:"> thead th, > thead td",selectorSort:"th, td",selectorRemove:".remove-me",debug:!1,headerList:[],empties:{},strings:{},parsers:[]};g.css={table:"tablesorter",cssHasChild:"tablesorter-hasChildRow",childRow:"tablesorter-childRow",header:"tablesorter-header",headerRow:"tablesorter-headerRow",headerIn:"tablesorter-header-inner",icon:"tablesorter-icon",info:"tablesorter-infoOnly",processing:"tablesorter-processing",sortAsc:"tablesorter-headerAsc",sortDesc:"tablesorter-headerDesc",
sortNone:"tablesorter-headerUnSorted"};g.language={sortAsc:"Ascending sort applied, ",sortDesc:"Descending sort applied, ",sortNone:"No sort applied, ",nextAsc:"activate to apply an ascending sort",nextDesc:"activate to apply a descending sort",nextNone:"activate to remove the sort"};g.log=a;g.benchmark=h;g.construct=function(d){return this.each(function(){var e=b.extend(!0,{},g.defaults,d);!this.hasInitialized&&g.buildTable&&"TABLE"!==this.tagName?g.buildTable(this,e):g.setup(this,e)})};g.setup=
function(d,e){if(!d||!d.tHead||0===d.tBodies.length||!0===d.hasInitialized)return e.debug?a("ERROR: stopping initialization! No table, thead, tbody or tablesorter has already been initialized"):"";var f="",c=b(d),m=b.metadata;d.hasInitialized=!1;d.isProcessing=!0;d.config=e;b.data(d,"tablesorter",e);e.debug&&b.data(d,"startoveralltimer",new Date);e.supportsTextContent="x"===b("<span>x</span>")[0].textContent;e.supportsDataObject=function(d){d[0]=parseInt(d[0],10);return 1<d[0]||1===d[0]&&4<=parseInt(d[1],
10)}(b.fn.jquery.split("."));e.string={max:1,min:-1,"max+":1,"max-":-1,zero:0,none:0,"null":0,top:!0,bottom:!1};/tablesorter\-/.test(c.attr("class"))||(f=""!==e.theme?" tablesorter-"+e.theme:"");e.$table=c.addClass(g.css.table+" "+e.tableClass+f).attr({role:"grid"});e.namespace=e.namespace?"."+e.namespace.replace(/\W/g,""):".tablesorter"+Math.random().toString(16).slice(2);e.$tbodies=c.children("tbody:not(."+e.cssInfoBlock+")").attr({"aria-live":"polite","aria-relevant":"all"});e.$table.find("caption").length&&
e.$table.attr("aria-labelledby","theCaption");e.widgetInit={};A(d);E(d);n(d);e.delayInit||w(d);g.bindEvents(d,e.$headers);H(d);e.supportsDataObject&&"undefined"!==typeof c.data().sortlist?e.sortList=c.data().sortlist:m&&c.metadata()&&c.metadata().sortlist&&(e.sortList=c.metadata().sortlist);g.applyWidget(d,!0);0<e.sortList.length?c.trigger("sorton",[e.sortList,{},!e.initWidgets,!0]):(C(d),e.initWidgets&&g.applyWidget(d));e.showProcessing&&c.unbind("sortBegin"+e.namespace+" sortEnd"+e.namespace).bind("sortBegin"+
e.namespace+" sortEnd"+e.namespace,function(e){g.isProcessing(d,"sortBegin"===e.type)});d.hasInitialized=!0;d.isProcessing=!1;e.debug&&g.benchmark("Overall initialization time",b.data(d,"startoveralltimer"));c.trigger("tablesorter-initialized",d);"function"===typeof e.initialized&&e.initialized(d)};g.isProcessing=function(d,e,a){d=b(d);var c=d[0].config;d=a||d.find("."+g.css.header);e?("undefined"!==typeof a&&0<c.sortList.length&&(d=d.filter(function(){return this.sortDisabled?!1:0<=g.isValueInArray(parseFloat(b(this).attr("data-column")),
c.sortList)})),d.addClass(g.css.processing+" "+c.cssProcessing)):d.removeClass(g.css.processing+" "+c.cssProcessing)};g.processTbody=function(d,e,a){d=b(d)[0];if(a)return d.isProcessing=!0,e.before('<span class="tablesorter-savemyplace"/>'),a=b.fn.detach?e.detach():e.remove();a=b(d).find("span.tablesorter-savemyplace");e.insertAfter(a);a.remove();d.isProcessing=!1};g.clearTableBody=function(d){b(d)[0].config.$tbodies.empty()};g.bindEvents=function(d,e){d=b(d)[0];var a,g=d.config;e.find(g.selectorSort).add(e.filter(g.selectorSort)).unbind(["mousedown",
"mouseup","sort","keyup",""].join(g.namespace+" ")).bind(["mousedown","mouseup","sort","keyup",""].join(g.namespace+" "),function(m,h){var k;k=m.type;if(!(1!==(m.which||m.button)&&!/sort|keyup/.test(k)||"keyup"===k&&13!==m.which||"mouseup"===k&&!0!==h&&250<(new Date).getTime()-a)){if("mousedown"===k)return a=(new Date).getTime(),"INPUT"===m.target.tagName?"":!g.cancelSelection;g.delayInit&&c(g.cache)&&w(d);k=/TH|TD/.test(this.tagName)?this:b(this).parents("th, td")[0];k=g.$headers[e.index(k)];k.sortDisabled||
K(d,k,m)}});g.cancelSelection&&e.attr("unselectable","on").bind("selectstart",!1).css({"user-select":"none",MozUserSelect:"none"})};g.restoreHeaders=function(d){var e=b(d)[0].config;e.$table.find(e.selectorHeaders).each(function(d){b(this).find("."+g.css.headerIn).length&&b(this).html(e.headerContent[d])})};g.destroy=function(d,e,a){d=b(d)[0];if(d.hasInitialized){g.refreshWidgets(d,!0,!0);var c=b(d),m=d.config,k=c.find("thead:first"),h=k.find("tr."+g.css.headerRow).removeClass(g.css.headerRow+" "+
m.cssHeaderRow),l=c.find("tfoot:first > tr").children("th, td");k.find("tr").not(h).remove();c.removeData("tablesorter").unbind("sortReset update updateAll updateRows updateCell addRows updateComplete sorton appendCache updateCache applyWidgetId applyWidgets refreshWidgets destroy mouseup mouseleave keypress sortBegin sortEnd ".split(" ").join(m.namespace+" "));m.$headers.add(l).removeClass([g.css.header,m.cssHeader,m.cssAsc,m.cssDesc,g.css.sortAsc,g.css.sortDesc,g.css.sortNone].join(" ")).removeAttr("data-column");
h.find(m.selectorSort).unbind(["mousedown","mouseup","keypress",""].join(m.namespace+" "));g.restoreHeaders(d);!1!==e&&c.removeClass(g.css.table+" "+m.tableClass+" tablesorter-"+m.theme);d.hasInitialized=!1;"function"===typeof a&&a(d)}};g.regex={chunk:/(^([+\-]?(?:0|[1-9]\d*)(?:\.\d*)?(?:[eE][+\-]?\d+)?)?$|^0x[0-9a-f]+$|\d+)/gi,chunks:/(^\\0|\\0$)/,hex:/^0x[0-9a-f]+$/i};g.sortNatural=function(d,e){if(d===e)return 0;var a,b,c,k,h,l;b=g.regex;if(b.hex.test(e)){a=parseInt(d.match(b.hex),16);c=parseInt(e.match(b.hex),
16);if(a<c)return-1;if(a>c)return 1}a=d.replace(b.chunk,"\\0$1\\0").replace(b.chunks,"").split("\\0");b=e.replace(b.chunk,"\\0$1\\0").replace(b.chunks,"").split("\\0");l=Math.max(a.length,b.length);for(h=0;h<l;h++){c=isNaN(a[h])?a[h]||0:parseFloat(a[h])||0;k=isNaN(b[h])?b[h]||0:parseFloat(b[h])||0;if(isNaN(c)!==isNaN(k))return isNaN(c)?1:-1;typeof c!==typeof k&&(c+="",k+="");if(c<k)return-1;if(c>k)return 1}return 0};g.sortNaturalAsc=function(d,e,a,b,c){if(d===e)return 0;a=c.string[c.empties[a]||c.emptyTo];
return""===d&&0!==a?"boolean"===typeof a?a?-1:1:-a||-1:""===e&&0!==a?"boolean"===typeof a?a?1:-1:a||1:g.sortNatural(d,e)};g.sortNaturalDesc=function(d,a,b,c,k){if(d===a)return 0;b=k.string[k.empties[b]||k.emptyTo];return""===d&&0!==b?"boolean"===typeof b?b?-1:1:b||1:""===a&&0!==b?"boolean"===typeof b?b?1:-1:-b||-1:g.sortNatural(a,d)};g.sortText=function(d,a){return d>a?1:d<a?-1:0};g.getTextValue=function(a,b,f){if(f){var c=a?a.length:0,g=f+b;for(f=0;f<c;f++)g+=a.charCodeAt(f);return b*g}return 0};
g.sortNumericAsc=function(a,b,f,c,k,h){if(a===b)return 0;h=h.config;k=h.string[h.empties[k]||h.emptyTo];if(""===a&&0!==k)return"boolean"===typeof k?k?-1:1:-k||-1;if(""===b&&0!==k)return"boolean"===typeof k?k?1:-1:k||1;isNaN(a)&&(a=g.getTextValue(a,f,c));isNaN(b)&&(b=g.getTextValue(b,f,c));return a-b};g.sortNumericDesc=function(a,b,f,c,k,h){if(a===b)return 0;h=h.config;k=h.string[h.empties[k]||h.emptyTo];if(""===a&&0!==k)return"boolean"===typeof k?k?-1:1:k||1;if(""===b&&0!==k)return"boolean"===typeof k?
k?1:-1:-k||-1;isNaN(a)&&(a=g.getTextValue(a,f,c));isNaN(b)&&(b=g.getTextValue(b,f,c));return b-a};g.sortNumeric=function(a,b){return a-b};g.characterEquivalents={a:"\u00e1\u00e0\u00e2\u00e3\u00e4\u0105\u00e5",A:"\u00c1\u00c0\u00c2\u00c3\u00c4\u0104\u00c5",c:"\u00e7\u0107\u010d",C:"\u00c7\u0106\u010c",e:"\u00e9\u00e8\u00ea\u00eb\u011b\u0119",E:"\u00c9\u00c8\u00ca\u00cb\u011a\u0118",i:"\u00ed\u00ec\u0130\u00ee\u00ef\u0131",I:"\u00cd\u00cc\u0130\u00ce\u00cf",o:"\u00f3\u00f2\u00f4\u00f5\u00f6",O:"\u00d3\u00d2\u00d4\u00d5\u00d6",
ss:"\u00df",SS:"\u1e9e",u:"\u00fa\u00f9\u00fb\u00fc\u016f",U:"\u00da\u00d9\u00db\u00dc\u016e"};g.replaceAccents=function(a){var b,f="[",c=g.characterEquivalents;if(!g.characterRegex){g.characterRegexArray={};for(b in c)"string"===typeof b&&(f+=c[b],g.characterRegexArray[b]=RegExp("["+c[b]+"]","g"));g.characterRegex=RegExp(f+"]")}if(g.characterRegex.test(a))for(b in c)"string"===typeof b&&(a=a.replace(g.characterRegexArray[b],b));return a};g.isValueInArray=function(a,b){var f,c=b.length;for(f=0;f<
c;f++)if(b[f][0]===a)return f;return-1};g.addParser=function(a){var b,f=g.parsers.length,c=!0;for(b=0;b<f;b++)g.parsers[b].id.toLowerCase()===a.id.toLowerCase()&&(c=!1);c&&g.parsers.push(a)};g.getParserById=function(a){var b,f=g.parsers.length;for(b=0;b<f;b++)if(g.parsers[b].id.toLowerCase()===a.toString().toLowerCase())return g.parsers[b];return!1};g.addWidget=function(b){g.widgets.push(b)};g.getWidgetById=function(b){var a,f,c=g.widgets.length;for(a=0;a<c;a++)if((f=g.widgets[a])&&f.hasOwnProperty("id")&&
f.id.toLowerCase()===b.toLowerCase())return f};g.applyWidget=function(a,e){a=b(a)[0];var f=a.config,c=f.widgetOptions,k=[],l,p,n;f.debug&&(l=new Date);f.widgets.length&&(f.widgets=b.grep(f.widgets,function(a,d){return b.inArray(a,f.widgets)===d}),b.each(f.widgets||[],function(a,b){(n=g.getWidgetById(b))&&n.id&&(n.priority||(n.priority=10),k[a]=n)}),k.sort(function(a,b){return a.priority<b.priority?-1:a.priority===b.priority?0:1}),b.each(k,function(g,k){if(k){if(e||!f.widgetInit[k.id])k.hasOwnProperty("options")&&
(c=a.config.widgetOptions=b.extend(!0,{},k.options,c)),k.hasOwnProperty("init")&&k.init(a,k,f,c),f.widgetInit[k.id]=!0;!e&&k.hasOwnProperty("format")&&k.format(a,f,c,!1)}}));f.debug&&(p=f.widgets.length,h("Completed "+(!0===e?"initializing ":"applying ")+p+" widget"+(1!==p?"s":""),l))};g.refreshWidgets=function(d,e,f){d=b(d)[0];var c,k=d.config,h=k.widgets,p=g.widgets,l=p.length;for(c=0;c<l;c++)p[c]&&p[c].id&&(e||0>b.inArray(p[c].id,h))&&(k.debug&&a('Refeshing widgets: Removing "'+p[c].id+'"'),p[c].hasOwnProperty("remove")&&
k.widgetInit[p[c].id]&&(p[c].remove(d,k,k.widgetOptions),k.widgetInit[p[c].id]=!1));!0!==f&&g.applyWidget(d,e)};g.getData=function(a,e,c){var k="";a=b(a);var g,h;if(!a.length)return"";g=b.metadata?a.metadata():!1;h=" "+(a.attr("class")||"");"undefined"!==typeof a.data(c)||"undefined"!==typeof a.data(c.toLowerCase())?k+=a.data(c)||a.data(c.toLowerCase()):g&&"undefined"!==typeof g[c]?k+=g[c]:e&&"undefined"!==typeof e[c]?k+=e[c]:" "!==h&&h.match(" "+c+"-")&&(k=h.match(RegExp("\\s"+c+"-([\\w-]+)"))[1]||
"");return b.trim(k)};g.formatFloat=function(a,e){if("string"!==typeof a||""===a)return a;var c;a=(e&&e.config?!1!==e.config.usNumberFormat:"undefined"!==typeof e?e:1)?a.replace(/,/g,""):a.replace(/[\s|\.]/g,"").replace(/,/g,".");/^\s*\([.\d]+\)/.test(a)&&(a=a.replace(/^\s*\(([.\d]+)\)/,"-$1"));c=parseFloat(a);return isNaN(c)?b.trim(a):c};g.isDigit=function(a){return isNaN(a)?/^[\-+(]?\d+[)]?$/.test(a.toString().replace(/[,.'"\s]/g,"")):!0}}});var c=b.tablesorter;b.fn.extend({tablesorter:c.construct});
c.addParser({id:"text",is:function(){return!0},format:function(a,h){var l=h.config;a&&(a=b.trim(l.ignoreCase?a.toLocaleLowerCase():a),a=l.sortLocaleCompare?c.replaceAccents(a):a);return a},type:"text"});c.addParser({id:"digit",is:function(a){return c.isDigit(a)},format:function(a,h){var l=c.formatFloat((a||"").replace(/[^\w,. \-()]/g,""),h);return a&&"number"===typeof l?l:a?b.trim(a&&h.config.ignoreCase?a.toLocaleLowerCase():a):a},type:"numeric"});c.addParser({id:"currency",is:function(a){return/^\(?\d+[\u00a3$\u20ac\u00a4\u00a5\u00a2?.]|[\u00a3$\u20ac\u00a4\u00a5\u00a2?.]\d+\)?$/.test((a||
"").replace(/[+\-,. ]/g,""))},format:function(a,h){var l=c.formatFloat((a||"").replace(/[^\w,. \-()]/g,""),h);return a&&"number"===typeof l?l:a?b.trim(a&&h.config.ignoreCase?a.toLocaleLowerCase():a):a},type:"numeric"});c.addParser({id:"ipAddress",is:function(a){return/^\d{1,3}[\.]\d{1,3}[\.]\d{1,3}[\.]\d{1,3}$/.test(a)},format:function(a,b){var l,s=a?a.split("."):"",n="",w=s.length;for(l=0;l<w;l++)n+=("00"+s[l]).slice(-3);return a?c.formatFloat(n,b):a},type:"numeric"});c.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\//.test(a)},
format:function(a){return a?b.trim(a.replace(/(https?|ftp|file):\/\//,"")):a},type:"text"});c.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}/.test(a)},format:function(a,b){return a?c.formatFloat(""!==a?(new Date(a.replace(/-/g,"/"))).getTime()||a:"",b):a},type:"numeric"});c.addParser({id:"percent",is:function(a){return/(\d\s*?%|%\s*?\d)/.test(a)&&15>a.length},format:function(a,b){return a?c.formatFloat(a.replace(/%/g,""),b):a},type:"numeric"});c.addParser({id:"usLongDate",
is:function(a){return/^[A-Z]{3,10}\.?\s+\d{1,2},?\s+(\d{4})(\s+\d{1,2}:\d{2}(:\d{2})?(\s+[AP]M)?)?$/i.test(a)||/^\d{1,2}\s+[A-Z]{3,10}\s+\d{4}/i.test(a)},format:function(a,b){return a?c.formatFloat((new Date(a.replace(/(\S)([AP]M)$/i,"$1 $2"))).getTime()||a,b):a},type:"numeric"});c.addParser({id:"shortDate",is:function(a){return/(^\d{1,2}[\/\s]\d{1,2}[\/\s]\d{4})|(^\d{4}[\/\s]\d{1,2}[\/\s]\d{1,2})/.test((a||"").replace(/\s+/g," ").replace(/[\-.,]/g,"/"))},format:function(a,b,l,s){if(a){l=b.config;
var n=l.$headers.filter("[data-column="+s+"]:last");s=n.length&&n[0].dateFormat||c.getData(n,l.headers[s],"dateFormat")||l.dateFormat;a=a.replace(/\s+/g," ").replace(/[\-.,]/g,"/");"mmddyyyy"===s?a=a.replace(/(\d{1,2})[\/\s](\d{1,2})[\/\s](\d{4})/,"$3/$1/$2"):"ddmmyyyy"===s?a=a.replace(/(\d{1,2})[\/\s](\d{1,2})[\/\s](\d{4})/,"$3/$2/$1"):"yyyymmdd"===s&&(a=a.replace(/(\d{4})[\/\s](\d{1,2})[\/\s](\d{1,2})/,"$1/$2/$3"))}return a?c.formatFloat((new Date(a)).getTime()||a,b):a},type:"numeric"});c.addParser({id:"time",
is:function(a){return/^(([0-2]?\d:[0-5]\d)|([0-1]?\d:[0-5]\d\s?([AP]M)))$/i.test(a)},format:function(a,b){return a?c.formatFloat((new Date("2000/01/01 "+a.replace(/(\S)([AP]M)$/i,"$1 $2"))).getTime()||a,b):a},type:"numeric"});c.addParser({id:"metadata",is:function(){return!1},format:function(a,c,l){a=c.config;a=a.parserMetadataName?a.parserMetadataName:"sortValue";return b(l).metadata()[a]},type:"numeric"});c.addWidget({id:"zebra",priority:90,format:function(a,h,l){var s,n,w,r,B,k,A=RegExp(h.cssChildRow,
"i"),y=h.$tbodies;h.debug&&(B=new Date);for(a=0;a<y.length;a++)s=y.eq(a),k=s.children("tr").length,1<k&&(w=0,s=s.children("tr:visible").not(h.selectorRemove),s.each(function(){n=b(this);A.test(this.className)||w++;r=0===w%2;n.removeClass(l.zebra[r?1:0]).addClass(l.zebra[r?0:1])}));h.debug&&c.benchmark("Applying Zebra widget",B)},remove:function(a,c,l){var s;c=c.$tbodies;var n=(l.zebra||["even","odd"]).join(" ");for(l=0;l<c.length;l++)s=b.tablesorter.processTbody(a,c.eq(l),!0),s.children().removeClass(n),
b.tablesorter.processTbody(a,s,!1)}})}(jQuery);var pukiwiki={};
(function(b,c,a){var h=[],l=[],s=[],n=[];if(!b)throw"pukiwiki: jQuery not included.";if(DEBUG){c.log=function(){log.history=log.history||[];log.history.push(arguments);if(this.console){var a=arguments;a.callee=a.callee.caller;a=[].slice.call(a);"object"===typeof console.log?log.apply.call(console.log,console,a):console.log.apply(console,a)}};var w;try{console.log(),w=c.console}catch(r){w=c.console={}}(function(a){function b(){}for(var c="assert count debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd time timeEnd trace warn".split(" "),
h;h=c.pop();)a[h]=a[h]||b})(w);c.console.debugMode=!0;var B=new Date}pukiwiki={config:{tablesorter:{counter:0,sorter:{useUI:!0,cssUI:{widget:"",header:"ui-btn-up-b",hover:"ui-btn-hover-b",icon:"ui-icon ui-icon-arrow-d ui-icon-shadow",iconBoth:"ui-icon-triangle-2-n-s",iconDesc:"ui-icon-arrow-u",iconAsc:"ui-icon-arrow-d"}},pager:{minimum_lines:5,size:[10,25,50,75,100],location_before:!0,positionFixed:!1}},syntaxhighlighter:{theme:"Default",brushes:["Plain","Diff"],config:{useScriptTags:!1}}},init:function(){DEBUG&&
console.info("PukiWiki Advance Mobile Debug mode. \nUsing jQuery: ",b.fn.jquery," / jQuery mobile: ",b.mobile.version);this.image_dir=IMAGE_URI+"ajax/";b.i18n(LANG);b.mobile.page.prototype.options.backBtnText=b.i18n("dialog","back");b.mobile.page.prototype.options.addBackBtn=!0;b.mobile.page.prototype.options.backBtnTheme="a";b.mobile.page.prototype.options.headerTheme="a";b.mobile.page.prototype.options.contentTheme="c";b.mobile.page.prototype.options.footerTheme="a";b.mobile.listview.prototype.options.headerTheme=
"a";b.mobile.listview.prototype.options.theme="c";b.mobile.listview.prototype.options.dividerTheme="b";b.mobile.listview.prototype.options.splitTheme="c";b.mobile.listview.prototype.options.countTheme="c";b.mobile.listview.prototype.options.filterTheme="c";b.mobile.listview.prototype.options.filterPlaceholder=b.i18n("dialog","filter");b.mobile.dialog.prototype.options.theme="d";b.mobile.dialog.prototype.options.closeBtnText=b.i18n("dialog","close");b.mobile.selectmenu.prototype.options.menuPageTheme=
"b";b.mobile.selectmenu.prototype.options.overlayTheme="b";b.mobile.selectmenu.prototype.options.closeText=b.i18n("dialog","close");b.mobile.loadingMessage=b.i18n("dialog","loading");b.mobile.loadingMessageTheme="a";b.mobile.pageLoadErrorMessage=b.i18n("dialog","error_page");b.mobile.pageLoadErrorMessageTheme="e"},init_dom:function(a,h){var l=this;a=a?a+" ":'*[role="main"] ';b(a+"img").bind("taphold",function(){c.open(b(this).attr("src"))});b(a+"#contents ul").listview();this.glossaly(a);this.bad_behavior(a);
this.tablesorter(a);b(a+"a").each(function(){var a=b(this),c=a.attr("href");a.data("ajax")&&a.data("ajax");c.match(/^#\w+?/)&&(a.data("ajax",!1),a.on("tap",function(){l.scrollTo(c);return!1}))});b(".to_header").on("tap",function(){l.scrollTo(".ui-page-active header")});b(".to_footer").on("tap",function(){l.scrollTo(".ui-page-active footer")})},scrollTo:function(a){var h;h=b(c);0===h.scrollTop()&&h.scrollTop(1);if(0<b("html").scrollTop())h=b("html");else if(0<b("body").scrollTop())h=b("body");else return;
h.stop().animate({scrollTop:b(a).offset().top},{duration:800})},tablesorter:function(a){var c=this,h=function(a){return['<div class="table_pager_widget ui-helper-clearfix" id="'+a+'">','<div class="ui-corner-all ui-controlgroup ui-controlgroup-horizontal">','<a href="#" class="prev" data-role="button" data-icon="arrow-l" data-iconpos="notext">'+b.i18n("dialog","prev")+"</a>",'<input class="pagedisplay" type="text" disabled="disabled" size="8" />','<a href="#" class="next" data-role="button" data-icon="arrow-r" data-iconpos="notext">'+
b.i18n("dialog","next")+"</a>",'<select class="pagesize"></select>\n</div>\n</div>'].join("\n")};b(".style_table").each(function(a){a=b(this);a.clone();var k=a.data(),l=c.config.tablesorter,n="undefined"===typeof a.data("sortable")||!0===a.data("sortable")?!0:!1;if(0!==a.find("thead").length&&n){if(b("tr",this).length>l.pager.minimum_lines&&0!==b("thead",this).length){n="table_pager_"+l.counter;l.sorter.headers=k.headers;l.sorter.sortList=k.sortList;l.sorter.parsers=k.parsers;a.tablesorter(l.sorter);
!0===l.pager.location_before?a.before(h(n)):a.after(h(n));for(k=0;k<l.pager.size.length;)b("#"+n+" .pagesize").append(b("<option>").attr({value:l.pager.size[k]}).text(l.pager.size[k])),k++;a.tablesorterPager({container:b("#"+n),positionFixed:!1,onthrough:function(a){c.glossaly(a)}});b("#"+n).show("clip");l.counter++}else a.tablesorter(l.sorter);a.data("enabled",!0)}})},glossaly:function(){b('[aria-describedby="tooltip"]:not(a)').each(function(){var a=b(this),c=a.data("msgtext")?a.data("msgtext"):
a.attr("title")?a.attr("title"):"";a.removeAttr("title");a.bind("tap",function(){b.mobile.showPageLoadingMsg();if(""===c){var h;b.ajax({url:SCRIPT,type:"GET",cache:!0,timeout:2E3,dataType:"xml",data:{cmd:"tooltip",q:a.text(),cache:!0},async:!1,success:function(a){h=a.documentElement.textContent;b.mobile.hidePageLoadingMsg()},complete:function(l,n){c=h;a.data("msgtext",h);b.mobile.showPageLoadingMsg(b.mobile.page.prototype.options.headerTheme,h,!0);setTimeout(function(){b.mobile.hidePageLoadingMsg()},
3E3)}})}else b.mobile.showPageLoadingMsg(b.mobile.page.prototype.options.headerTheme,c,!0),setTimeout(function(){b.mobile.hidePageLoadingMsg()},3E3)})})},sh:function(a){a=a?a+" .sh":".sh";0!==b(a).length&&(this.config.syntaxhighlighter={baseUrl:JS_URI+"syntaxhighlighter/",target:a,config:{strings:{expandSource:b.i18n("sh","expandSource"),viewSource:b.i18n("sh","viewSource"),copyToClipboard:b.i18n("sh","copyToClipboard"),copyToClipboardConfirmation:b.i18n("sh","copyToClipboardConfirmation"),print:b.i18n("sh",
"print"),noBrush:b.i18n("sh","noBrush"),brushNotHtmlScript:b.i18n("sh","brushNotHtmlScript")}}},b.beautyOfCode.beautifyAll(this.config.syntaxhighlighter))},bad_behavior:function(a){"undefined"!==typeof BH_NAME&&"undefined"!==typeof BH_VALUE&&b((a?a+" ":"")+"form").append('<input type="hidden" name="'+BH_NAME+'" value="'+BH_VALUE+'" />')},register:{init:function(a){h.push(a)},before_init:function(a){l.push(a)},unload:function(a){s.push(a)},before_unload:function(a){n.push(a)}}};b(a).ready(function(){var a=
"jquery.mobile-"+JQUERY_MOBILE_VER+(DEBUG?"":".min");"latest"!==JQUERY_MOBILE_VER?(b("head").prepend('<link rel="stylesheet" href="http://code.jquery.com/mobile/'+JQUERY_MOBILE_VER+"/"+a+'.css" />'),b.getScript("http://code.jquery.com/mobile/"+JQUERY_MOBILE_VER+"/"+a+".js",function(){b("html").fadeIn("fast");b("html").css("display","block")})):(b("head").prepend('<link rel="stylesheet" href="http://code.jquery.com/mobile/latest/jquery.mobile.css" />'),b.getScript("http://code.jquery.com/mobile/latest/jquery.mobile.js",
function(){b("html").fadeIn("fast");b("html").css("display","block")}))});b(a).bind("mobileinit",function(){var a=b('[data-role="page"]');if(DEBUG){var n=new Date;console.info("jQuery mobile loaded. (Process Time :",n-B,"ms)")}pukiwiki.init();"undefined"!==typeof GOOGLE_ANALYTICS&&(c._gaq=[["_setAccount",GOOGLE_ANALYTICS],["_trackPageview"],["_trackPageLoadTime"]],b.getScript(("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js"));a.on("pageload",function(a,b){for(var c;c=l.shift();)null!==
c&&c()}).on("pageshow",function(a,k){pukiwiki.init_dom();for(var l;l=h.shift();)null!==l&&l();c._gaq&&_gaq.push(["_trackPageview",b.mobile.activePage.jqmData("url")])});var r=b("#adarea_content");if(0!==r.length){var s=b("#adarea_content").find("iframe");b(s).appendTo(".adarea");r.remove();a.on("pagehide",function(a,c){b(s).appendTo(".adarea")})}DEBUG&&(a=new Date,console.info("Finish. (Process Time :",a-n,"ms / Total :",a-B,"ms)"));b.mobile.page.prototype.options.addBackBtn=!0})})(jQuery,this,this.document);
