(function(a,d,c){a.beautyOfCode={settings:{autoLoad:!0,baseUrl:"http://alexgorbatchev.com.s3.amazonaws.com/pub/sh/2.1.382/",scripts:"scripts/",styles:"styles/",theme:"Default",brushes:["Plain"],target:".sh",config:{debug:!1},defaults:{},ready:function(){a.beautyOfCode.beautifyAll()}},init:function(b){b=a.extend({},a.beautyOfCode.settings,b);b.config.clipboardSwf||(b.config.clipboardSwf=b.baseUrl+b.scripts+"clipboard.swf");a(c).ready(function(){if(b.autoLoad){a.beautyOfCode.utils.loadCss(b.baseUrl+
b.styles+"shCore.css");a.beautyOfCode.utils.loadCss(b.baseUrl+b.styles+"shTheme"+b.theme+".css","shTheme");var c=[];b.debug==true?c.push(b.baseUrl+"src/shCore.js"):c.push(b.baseUrl+b.scripts+"shCore.js");a.each(b.brushes,function(a,f){c.push(b.baseUrl+b.scripts+"shBrush"+f+".js")});a.beautyOfCode.utils.loadAllScripts(c,function(){b&&b.config&&a.extend(SyntaxHighlighter.config,b.config);b&&b.defaults&&a.extend(SyntaxHighlighter.defaults,b.defaults);b.ready()})}else b.ready()})},beautifyAll:function(b){var b=
a.extend({},a.beautyOfCode.settings,b),c=this;a(b.target).each(function(){var e=a(this);c.dom_cache.push(e);e=c.utils.getBrush(e.data().brush);-1===a.inArray(e,b.brushes)&&b.brushes.push(e)});b.ready=function(){for(var a=0;a<=c.dom_cache.length-1;a++){var b=c.dom_cache[a];b.beautifyCode(b.data().brush)}};a.beautyOfCode.init(b)},dom_cache:[],utils:{loaded:[],loadScript:function(b,c){var e=this;-1===a.inArray(b,this.loaded)?a.ajax({url:b,complete:function(){c();e.loaded.push(b)},type:"GET",dataType:"script",
cache:!0}):c()},loadAllScripts:function(b,c){!b||0==b.length?c():a.beautyOfCode.utils.loadScript(b[0],function(){a.beautyOfCode.utils.loadAllScripts(b.slice(1,b.length),c)})},loadCss:function(b,g){var e=a("head")[0];if(b&&e){var f=c.createElement("link");f.setAttribute("rel","stylesheet");f.setAttribute("href",b);g&&(f.id=g);e.appendChild(f)}},addCss:function(b,g){var e=a("head")[0];if(b&&e){var f=c.createElement("style");f.setAttribute("type","text/css");g&&(f.id=g);f.styleSheet?f.styleSheet.cssText=
b:a(f).text(b);e.appendChild(f)}},addCssForBrush:function(c,g){c.isCssInitialized||(a.beautyOfCode.utils.addCss(g.Style),c.isCssInitialized=!0)},getBrush:function(a){var c={AppleScript:["applescript"],AS3:["actionscript3","as3","as"],Bash:["bash","shell"],ColdFusion:["coldfusion","cf"],Cpp:["cpp","c","h","hpp"],CSharp:["c#","c-sharp","csharp","cs"],Css:["css"],Delphi:["delphi","pascal","pas"],Diff:["diff","patch"],Erlang:["erl","erlang"],Groovy:["groovy"],Java:["java"],JavaFX:["jfx","javafx"],JScript:["js",
"jscript","javascript","json"],Perl:["perl","pl"],Php:["php"],Plain:["text","plain"],Python:["py","python"],Ruby:["ruby","rails","ror","rb"],Sass:["sass","scss"],Scala:["scala"],Sql:["sql"],Vb:["vb","vbnet"],Xml:["xml","xhtml","xslt","html"]},e;for(e in c)for(var f=0;f<=c[e].length-1;f++)if(c[e][f]==a)return e;return"Plain"}}};a.fn.beautifyCode=function(c,g){this.each(function(c,b){var j=a(b),d=j.data(),h={"class-name":d.className,"first-line":d.firstLine,"tab-size":d.tabSize,"smart-tabs":d.smartTabs,
ruler:d.ruler,gutter:d.gutter,highlight:d.highlight,toolbar:d.toolbar,collapse:d.collapse,"auto-links":d.autoLinks,light:d.light,"wrap-lines":d.warpLines,"html-script":d.htmlScript},d=d.brush?d.brush:"plain",i=j.text();a.browser.msie&&9<a.browser.version&&(i=i.replace(/\x0D\x0A|\x0D|\x0A/g,"\n\r"));h=a.extend({},SyntaxHighlighter.defaults,g,h);if(!0==h["html-script"])highlighter=new SyntaxHighlighter.HtmlScript(d);else if(d=SyntaxHighlighter.utils.findBrush(d))highlighter=new d;else return;a.beautyOfCode.utils.addCssForBrush(d,
highlighter);highlighter.highlight(i,h);highlighter.source=b;j.replaceWith(highlighter.div)})}})(jQuery,this,this.document);
(function(a){a._i18n={trans:{},"default":"en",language:"en"};a.i18n=function(){if(2>arguments.length)return a._i18n.language=arguments[0],a._i18n.language;if("string"==typeof arguments[1]){var d;d=arguments[0];var c=arguments[1],b=!1;a._i18n.trans[a._i18n.language]&&a._i18n.trans[a._i18n.language][d]&&a._i18n.trans[a._i18n.language][d][c]?b=a._i18n.trans[a._i18n.language][d][c]:a._i18n.trans[a._i18n["default"]]&&a._i18n.trans[a._i18n["default"]][d]&&a._i18n.trans[a._i18n["default"]][d][c]&&(b=a._i18n.trans[a._i18n["default"]][d][c]);
d=b||c;return arguments[2]&&"object"==typeof arguments[2]?a.format(d,arguments[2]):d}c=arguments[0].split(".");d=c[0];c=c[1]||"jQuery";a._i18n.trans[d]||(a._i18n.trans[d]={});a._i18n.trans[d][c]?a.extend(a._i18n.trans[d][c],arguments[1]):a._i18n.trans[d][c]=arguments[1]}})(jQuery);
(function(a,d,c){a.fn.lazyload=function(b){var g=function(b){b=a(b).offset();/; CPU.*OS (?:3_2|4_0)/i.test(navigator.userAgent)&&"getBoundingClientRect"in c.documentElement&&(b.top-=d.scrollY,b.left-=d.scrollX);return b},e=this,f={threshold:0,container:d,effect:"show",namespace:".lazyload"};b&&a.extend(f,b);var j=a(f.container),l=f.namespace,h="appear"+l,b="resize"+l,i="scroll"+l,k=function(c){c=a(c);if(!c.length)return!1;var b=f.threshold,e;if(j[0]===d)var i=j.height()+j.scrollTop(),k=j.scrollLeft(),
h=j.width()+j.scrollLeft(),l=j.scrollTop();else e=g(j),i=e.top+j.height(),k=e.left,h=e.left+j.width(),l=e.top;e=g(c);var s=e.top+c.height(),x=e.left,c=e.left+c.width();return e.top+b<=i&&x+b<=h&&s-b>=l&&c-b>k};e.each(function(){var c=this,b=a(this);if(k(b)&&!b.attr("original"))c.loaded=!0;else if(!(0==c.offsetWidth||0==c.offsetHeight||""==b.attr("href","src"))){b.data("original",b.attr("original")||b.attr("src"));if(!b.attr("src")||f.placeholder===b.attr("src")||!k(b))f.placeholder?b.attr("src",f.placeholder):
b.removeAttr("src"),c.loaded=!1;b.one(h,function(){this.loaded||a("<img />").load(function(){b.hide().attr("src",b.data("original"))[f.effect](f.effectSpeed).removeData("original");c.loaded=!0}).attr("src",b.data("original"))})}});j.bind(i+" "+b,function(){e.each(function(){k(this)&&!this.loaded&&$e.trigger(h)});e=a(a.grep(e,function(a){return!a.loaded}));e.length||j.unbind(l)}).trigger(i);return this}})(jQuery,window,document);
(function(a){function d(a){return"object"==typeof a?a:{top:a,left:a}}var c=a.scrollTo=function(c,d,e){a(window).scrollTo(c,d,e)};c.defaults={axis:"xy",duration:1.3<=parseFloat(a.fn.jquery)?0:1};c.window=function(){return a(window)._scrollable()};a.fn._scrollable=function(){return this.map(function(){if(this.nodeName&&-1==a.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"]))return this;var c=(this.contentWindow||this).document||this.ownerDocument||this;return a.browser.safari||
"BackCompat"==c.compatMode?c.body:c.documentElement})};a.fn.scrollTo=function(b,g,e){"object"==typeof g&&(e=g,g=0);"function"==typeof e&&(e={onAfter:e});"max"==b&&(b=9E9);e=a.extend({},c.defaults,e);g=g||e.speed||e.duration;e.queue=e.queue&&1<e.axis.length;e.queue&&(g/=2);e.offset=d(e.offset);e.over=d(e.over);return this._scrollable().each(function(){function f(a){l.animate(k,g,e.easing,a&&function(){a.call(this,b,e)})}var j=this,l=a(j),h=b,i,k={},o=l.is("html,body");switch(typeof h){case "number":case "string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(h)){h=
d(h);break}h=a(h,this);case "object":if(h.is||h.style)i=(h=a(h)).offset()}a.each(e.axis.split(""),function(a,b){var d=b=="x"?"Left":"Top",g=d.toLowerCase(),m="scroll"+d,q=j[m],s=c.max(j,b);if(i){k[m]=i[g]+(o?0:q-l.offset()[g]);if(e.margin){k[m]=k[m]-(parseInt(h.css("margin"+d))||0);k[m]=k[m]-(parseInt(h.css("border"+d+"Width"))||0)}k[m]=k[m]+(e.offset[g]||0);e.over[g]&&(k[m]=k[m]+h[b=="x"?"width":"height"]()*e.over[g])}else{d=h[g];k[m]=d.slice&&d.slice(-1)=="%"?parseFloat(d)/100*s:d}/^\d+$/.test(k[m])&&
(k[m]=k[m]<=0?0:Math.min(k[m],s));if(!a&&e.queue){q!=k[m]&&f(e.onAfterFirst);delete k[m]}});f(e.onAfter)}).end()};c.max=function(c,d){var e="x"==d?"Width":"Height",f="scroll"+e;if(!a(c).is("html,body"))return c[f]-a(c)[e.toLowerCase()]();var e="client"+e,j=c.ownerDocument.documentElement,l=c.ownerDocument.body;return Math.max(j[f],l[f])-Math.min(j[e],l[e])}})(jQuery);
(function(a){a.extend({tablesorter:new function(){function c(a,c){b(a+","+((new Date).getTime()-c.getTime())+"ms")}function b(a){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(a):alert(a)}function d(c,i){if(c.config.debug)var u="";var f=c.tBodies[0].rows;if(c.tBodies[0].rows[0])for(var g=[],f=f[0].cells,k=f.length,h=0;h<k;h++){var r=!1;a.metadata&&a(i[h]).metadata()&&a(i[h]).metadata().sorter?r=e(a(i[h]).metadata().sorter):c.config.headers[h]&&c.config.headers[h].sorter&&
(r=e(c.config.headers[h].sorter));if(!r)a:{for(var r=c,o=f[h],l=q.length,p=1;p<l;p++)if(q[p].is(a.trim(j(r.config,o)),r,o)){r=q[p];break a}r=q[0]}c.config.debug&&(u+="column:"+h+" parser:"+r.id+"\n");g.push(r)}c.config.debug&&b(u);return g}function e(a){for(var c=q.length,b=0;b<c;b++)if(q[b].id.toLowerCase()==a.toLowerCase())return q[b];return!1}function f(b){if(b.config.debug)var e=new Date;for(var i=b.tBodies[0]&&b.tBodies[0].rows.length||0,d=b.tBodies[0].rows[0]&&b.tBodies[0].rows[0].cells.length||
0,f=b.config.parsers,g={row:[],normalized:[]},k=0;k<i;++k){var h=a(b.tBodies[0].rows[k]),o=[];if(h.hasClass(b.config.cssChildRow))g.row[g.row.length-1]=g.row[g.row.length-1].add(h);else{g.row.push(h);for(var l=0;l<d;++l)o.push(f[l].format(j(b.config,h[0].cells[l]),b,h[0].cells[l]));o.push(g.normalized.length);g.normalized.push(o)}}b.config.debug&&c("Building cache for "+i+" rows:",e);return g}function j(c,b){if(!b)return"";var e="";return e="simple"==c.textExtraction?b.childNodes[0]&&b.childNodes[0].hasChildNodes()?
b.childNodes[0].innerHTML:b.innerHTML:"function"==typeof c.textExtraction?c.textExtraction(b):a(b).text()}function l(b,e){if(b.config.debug)var i=new Date;for(var d=e.row,f=e.normalized,g=f.length,h=f[0].length-1,j=a(b.tBodies[0]),l=[],o=0;o<g;o++){var p=f[o][h];l.push(d[p]);if(!b.config.appender)for(var p=d[p],t=p.length,m=0;m<t;m++)j[0].appendChild(p[m])}b.config.appender&&b.config.appender(b,l);l=null;b.config.debug&&c("Rebuilt table:",i);k(b);setTimeout(function(){a(b).trigger("sortEnd")},0)}
function h(e){if(e.config.debug)var i=new Date;var d=e.config;$tableHeaders=a(d.selectorHeaders,e).each(function(c){this.column=c;this.count=this.order="Number"!=typeof d.sortInitialOrder?"desc"==d.sortInitialOrder.toLowerCase()?1:0:1==d.sortInitialOrder?1:0;if(a.metadata&&!1===a(this).metadata().sorter||e.config.headers[c]&&!1===e.config.headers[c].sorter)this.sortDisabled=!0;this.sortDisabled||(d.useUI?(a(this).prepend("<span></span>").children("span").addClass(d.cssUI.icon),a(this).hover(function(){a(this).addClass(d.cssUI.hover)},
function(){a(this).removeClass(d.cssUI.hover)})):d.onRenderHeader&&d.onRenderHeader.apply(this));d.headerList[c]=this});e.config.debug&&(c("Built headers:",i),b($tableHeaders));return $tableHeaders}function i(c,b){var e=c.config;if(e.useUI)return a(c).parent("div:first").addClass(e.cssUI.widget),b.addClass(e.cssUI.header),[e.cssUI.iconDesc,e.cssUI.iconAsc,e.cssUI.iconBoth];b.addClass(e.cssHeader);return[e.cssDesc,e.cssAsc]}function k(a){for(var c=a.config.widgets,b=c.length,e=0;e<b;e++)o(c[e]).format(a)}
function o(a){for(var c=s.length,b=0;b<c;b++)if(s[b].id.toLowerCase()==a.toLowerCase())return s[b]}function p(a,c){for(var b=c.length,e=0;e<b;e++)if(c[e][0]==a)return!0;return!1}function t(c,b,e,d){c=c.config;c.useUI?b.children("span").removeClass(d[0]).removeClass(d[1]).addClass(d[2]):b.removeClass(d[0]).removeClass(d[1]);var i=[];b.each(function(){this.sortDisabled||(i[this.column]=a(this))});for(var b=e.length,f=0;f<b;f++)c.useUI?i[e[f][0]].children("span").removeClass(d[2]).addClass(d[e[f][1]]):
i[e[f][0]].addClass(d[e[f][1]])}function w(c){if(c.config.widthFixed){var b=a("<colgroup>");a("tr:first td",c.tBodies[0]).each(function(){b.append(a("<col>").css("width",a(this).width()))});a(c).prepend(b)}}function v(a,b,e){if(a.config.debug)var d=new Date;for(var i="var sortWrapper = function(a,b) {",f=b.length,g=0;g<f;g++)var h=b[g][0],k=b[g][1],h="text"==a.config.parsers[h].type?0==k?m("text","asc",h):m("text","desc",h):0==k?m("numeric","asc",h):m("numeric","desc",h),j="e"+g,i=i+("var "+j+" = "+
h),i=i+("if("+j+") { return "+j+"; } "),i=i+"else { ";g=e.normalized[0].length-1;i+="return a["+g+"]-b["+g+"];";for(g=0;g<f;g++)i+="}; ";i+="return 0; }; ";a.config.debug&&c("Evaling expression:"+i,new Date);eval(i);e.normalized.sort(sortWrapper);a.config.debug&&c("Sorting on "+b.toString()+" and dir "+k+" time:",d);return e}function m(a,c,b){var e="a["+b+"]",b="b["+b+"]";if("text"==a&&"asc"==c)return"("+e+" == "+b+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : ("+
e+" < "+b+") ? -1 : 1 )));";if("text"==a&&"desc"==c)return"("+e+" == "+b+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : ("+b+" < "+e+") ? -1 : 1 )));";if("numeric"==a&&"asc"==c)return"("+e+" === null && "+b+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+b+"));";if("numeric"==a&&"desc"==c)return"("+e+" === null && "+b+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+
b+" === null ? Number.NEGATIVE_INFINITY : "+b+" - "+e+"));"}var q=[],s=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",cssUI:{widget:"ui-widget ui-widget-content ui-corner-all",header:"ui-widget-header ui-corner-all",hover:"ui-state-hover",icon:"ui-icon",iconBoth:"ui-icon-arrowthick-2-n-s",iconDesc:"ui-icon-arrowthick-1-n",iconAsc:"ui-icon-arrowthick-1-s"},sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,
textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],locale:"us",format:{us:{decimal:".",date:"/"},en:{decimal:".",date:"/"},eu:{decimal:",",date:"."},de:{decimal:",",date:"."}},onRenderHeader:null,selectorHeaders:"thead th",useUI:!1,debug:!1};this.benchmark=c;this.construct=function(b){return this.each(function(){if(this.tHead&&this.tBodies){var c,e,m,n;this.config={};n=a.extend(this.config,a.tablesorter.defaults,
b);c=a(this);a.data(this,"tablesorter",n);e=h(this);this.config.parsers=d(this,e);m=f(this);var q=i(this,e);w(this);e.click(function(b){var d=c[0].tBodies[0]&&c[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&0<d){c.trigger("sortStart");a(this);d=this.column;this.order=this.count++%2;if(b[n.sortMultiSortKey])if(p(d,n.sortList))for(b=0;b<n.sortList.length;b++){var i=n.sortList[b],f=n.headerList[i[0]];i[0]==d&&(f.count=i[1],f.count++,i[1]=f.count%2)}else n.sortList.push([d,this.order]);else{n.sortList=
[];if(null!=n.sortForce){i=n.sortForce;for(b=0;b<i.length;b++)i[b][0]!=d&&n.sortList.push(i[b])}n.sortList.push([d,this.order])}setTimeout(function(){t(c[0],e,n.sortList,q);l(c[0],v(c[0],n.sortList,m))},1);return!1}}).mousedown(function(){if(n.cancelSelection)return this.onselectstart=function(){return!1},!1});c.bind("update",function(){var a=this;setTimeout(function(){a.config.parsers=d(a,e);m=f(a)},1)}).bind("updateCell",function(a,b){var c=this.config,e=[b.parentNode.rowIndex-1,b.cellIndex];m.normalized[e[0]][e[1]]=
c.parsers[e[1]].format(j(c,b),b)}).bind("sorton",function(b,c){a(this).trigger("sortStart");n.sortList=c;for(var d=n.sortList,i=this.config,f=d.length,g=0;g<f;g++){var h=d[g],k=i.headerList[h[0]];k.count=h[1];k.count++}t(this,e,d,q);l(this,v(this,d,m))}).bind("appendCache",function(){l(this,m)}).bind("applyWidgetId",function(a,b){o(b).format(this)}).bind("applyWidgets",function(){k(this)});a.metadata&&a(this).metadata()&&a(this).metadata().sortlist&&(n.sortList=a(this).metadata().sortlist);0<n.sortList.length?
c.trigger("sorton",[n.sortList]):k(this)}})};this.addParser=function(a){for(var b=q.length,c=!0,e=0;e<b;e++)q[e].id.toLowerCase()==a.id.toLowerCase()&&(c=!1);c&&q.push(a)};this.addWidget=function(a){s.push(a)};this.formatDate=function(a,b){"us"!=b.locale&&(a=a.replace(RegExp("[\\-\\"+b.format[b.locale].date+"]","g"),b.format.us.date));return a};this.formatDecimal=function(a,b){"us"!=b.locale&&(a=a.replace(b.format[b.locale].decimal,b.format.us.decimal));return a};this.formatFloat=function(a){a=parseFloat(a);
return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(b,c){var e="\\"+c.format[c.locale].decimal;return RegExp("/(^[+]?0("+e+"0+)?$)|(^([-+]?[0-9]*)$)|(^([-+]?((0?[0-9]*)"+e+"(0*[0-9]*)))$)|(^[-+]?[0-9]*"+e+"0+$)/").test(a.trim(b))};this.clearTableBody=function(b){a.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(b.tBodies[0]):b.tBodies[0].innerHTML=""}}});a.fn.extend({tablesorter:a.tablesorter.construct});var d=
a.tablesorter;d.addParser({id:"text",is:function(){return!0},format:function(c){return a.trim(c.toLowerCase())},type:"text"});d.addParser({id:"digit",is:function(c,b){return a.tablesorter.isDigit(c,b.config)},format:function(c,b){c=a.tablesorter.formatDecimal(c,b.config);return a.tablesorter.formatFloat(c)},type:"numeric"});d.addParser({id:"currency",is:function(a){return/^[\uff82\uff63$\u7ac4\uff6c?.,]/.test(a)},format:function(c,b){c=a.tablesorter.formatDecimal(c,b.config);return a.tablesorter.formatFloat(c.replace(RegExp(/[\uff82\uff63$\u7ac4\uff6c]/g),
""))},type:"numeric"});d.addParser({id:"ipAddress",is:function(a){return/^\d{2,3}[\.]\d{1,3}[\.]\d{1,3}[\.]\d{1,3}$/.test(a)},format:function(c){for(var c=c.split("."),b="",d=c.length,e=0;e<d;e++)var f=c[e],b=2==f.length?b+("0"+f):b+f;return a.tablesorter.formatFloat(b)},type:"numeric"});d.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\/$/.test(a)},format:function(a){return jQuery.trim(a.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});d.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},
format:function(c){return a.tablesorter.formatFloat(""!=c?(new Date(c.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});d.addParser({id:"percent",is:function(c){return/\%$/.test(a.trim(c))},format:function(c,b){c=a.tablesorter.formatDecimal(c,b.config);return a.tablesorter.formatFloat(c.replace(RegExp(/%/g),""))},type:"numeric"});d.addParser({id:"usLongDate",is:function(a){return a.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},
format:function(c){return a.tablesorter.formatFloat((new Date(c)).getTime())},type:"numeric"});d.addParser({id:"mediumDate",is:function(a,b){var d=b.config,d="\\"+d.format[d.locale].date;return RegExp("\\d{1,2}[\\-"+d+"]\\d{1,2}[\\-"+d+"]\\d{4}").test(a)},format:function(c,b){var d=b.config,c=a.tablesorter.formatDate(c,d);if("us"==d.locale)c=c.replace(/(\d{1,2})[\/](\d{1,2})[\/](\d{4})/,"$3/$1/$2");else if("en"==d.locale||"de"==d.locale||"eu"==d.locale)c=c.replace(/(\d{1,2})[\/](\d{1,2})[\/](\d{4})/,
"$3/$2/$1");return a.tablesorter.formatFloat(""!=c?(new Date(c)).getTime():0)},type:"numeric"});d.addParser({id:"shortDate",is:function(a,b){var d=b.config,d="\\"+d.format[d.locale].date;return RegExp("\\d{1,2}[\\-"+d+"]\\d{1,2}[\\-"+d+"]\\d{2}").test(a)},format:function(c,b){var d=b.config,c=a.tablesorter.formatDate(c,d);if("us"==d.locale)c=c.replace(/(\d{1,2})[\/](\d{1,2})[\/](\d{2})/,"$1/$2/$3");else if("en"==d.locale||"de"==d.locale||"eu"==d.locale)c=c.replace(/(\d{1,2})[\/](\d{1,2})[\/](\d{2})/,
"$2/$1/$3");return a.tablesorter.formatFloat(""!=c?(new Date(c)).getTime():0)},type:"numeric"});d.addParser({id:"time",is:function(a){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(a)},format:function(c){return a.tablesorter.formatFloat((new Date("2000/01/01 "+c)).getTime())},type:"numeric"});d.addParser({id:"metadata",is:function(){return!1},format:function(c,b,d){c=b.config;c=!c.parserMetadataName?"sortValue":c.parserMetadataName;return a(d).metadata()[c]},type:"numeric"});
d.addWidget({id:"zebra",format:function(c){if(c.config.debug)var b=new Date;var d,e=-1,f;a("tr:visible",c.tBodies[0]).each(function(){d=a(this);d.hasClass(c.config.cssChildRow)||e++;f=0==e%2;d.removeClass(c.config.widgetZebra.css[f?0:1]).addClass(c.config.widgetZebra.css[f?1:0])});c.config.debug&&a.tablesorter.benchmark("Applying Zebra widget",b)}})})(jQuery);
(function(a){a.extend({tablesorterPager:new function(){var d=function(b){var c=b.config,b=a(b);!c.pagerPositionSet&&c.positionFixed&&(b.offset&&c.container.css({top:b.offset().top+b.height()+"px",position:"absolute"}),c.pagerPositionSet=!0)},c=function(b,c){var j,l,h,i,k=b.config,o=c.length;j=k.page*k.size;var p=j+k.size;a(b).trigger("pagerChange",k);p>c.length&&(p=c.length);i=a(b.tBodies[0]);for(a.tablesorter.clearTableBody(b);j<p;j++){h=c[j];o=h.length;for(l=0;l<o;l++)i[0].appendChild(h[l])}d(b,
i);a(b).trigger("applyWidgets");k.page>=k.totalPages&&g(b);a(k.cssPageDisplay,k.container).val(k.page+1+k.seperator+k.totalPages);a(b).trigger("pagerComplete",k)},b=function(a){var b=a.config;if(0>b.page||b.page>b.totalPages-1)b.page=0;c(a,b.rowsCopy)},g=function(a){var c=a.config;c.page=c.totalPages-1;b(a)};this.appender=function(a,b){var d=a.config;d.rowsCopy=b;d.totalRows=b.length;d.totalPages=Math.ceil(d.totalRows/d.size);c(a,b)};this.defaults={size:10,offset:0,page:0,totalRows:0,totalPages:0,
container:null,cssNext:".next",cssPrev:".prev",cssFirst:".first",cssLast:".last",cssPageDisplay:".pagedisplay",cssPageSize:".pagesize",seperator:"/",positionFixed:!0,appender:this.appender};this.construct=function(c){return this.each(function(){var f=a.extend(this.config,a.tablesorterPager.defaults,c),j=this,l=f.container;a(this).trigger("appendCache");f.size=parseInt(a(".pagesize",l).val(),10);a(f.cssFirst,l).click(function(){j.config.page=0;b(j);return!1});a(f.cssNext,l).click(function(){var a=
j.config;a.page++;a.page>=a.totalPages-1&&(a.page=a.totalPages-1);b(j);return!1});a(f.cssPrev,l).click(function(){var a=j.config;a.page--;0>=a.page&&(a.page=0);b(j);return!1});a(f.cssLast,l).click(function(){g(j);return!1});a(f.cssPageSize,l).change(function(){var c=parseInt(a(this).val(),10),e=j.config;e.size=c;e.totalPages=Math.ceil(e.totalRows/e.size);e.pagerPositionSet=!1;b(j);d(j);return!1})})}}});a.fn.extend({tablesorterPager:a.tablesorterPager.construct})})(jQuery);
var pukiwiki={},JQUERY_MOBILE_VER="1.1.0";
(function(a,d,c){var b=[],g=[],e=[],f=[];if(!a)throw"pukiwiki: jQuery not included.";if(DEBUG){d.log=function(){log.history=log.history||[];log.history.push(arguments);if(this.console){var a=arguments;a.callee=a.callee.caller;a=[].slice.call(a);"object"===typeof console.log?log.apply.call(console.log,console,a):console.log.apply(console,a)}};var j;try{console.log(),j=d.console}catch(l){j=d.console={}}(function(a){function b(){}for(var c="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),d;d=
c.pop();)a[d]=a[d]||b})(j);d.console.debugMode=!0;var h=new Date}pukiwiki={config:{tablesorter:{counter:0,sorter:{useUI:!0,cssUI:{widget:"",header:"ui-btn-up-b",hover:"ui-btn-hover-b",icon:"ui-icon ui-icon-arrow-d ui-icon-shadow",iconBoth:"ui-icon-triangle-2-n-s",iconDesc:"ui-icon-arrow-u",iconAsc:"ui-icon-arrow-d"}},pager:{minimum_lines:5,size:[10,25,50,75,100],location_before:!0,positionFixed:!1}},syntaxhighlighter:{theme:"Default",brushes:["Plain","Diff"],config:{useScriptTags:!1}}},init:function(){DEBUG&&
console.info("PukiWiki Advance Mobile Debug mode. \nUsing jQuery: ",a.fn.jquery," / jQuery mobile: ",JQUERY_MOBILE_VER);this.image_dir=IMAGE_URI+"ajax/";a.i18n(LANG);a.mobile.page.prototype.options.backBtnText=a.i18n("dialog","back");a.mobile.page.prototype.options.addBackBtn=!0;a.mobile.page.prototype.options.backBtnTheme="a";a.mobile.page.prototype.options.headerTheme="a";a.mobile.page.prototype.options.contentTheme="c";a.mobile.page.prototype.options.footerTheme="a";a.mobile.listview.prototype.options.headerTheme=
"a";a.mobile.listview.prototype.options.theme="c";a.mobile.listview.prototype.options.dividerTheme="b";a.mobile.listview.prototype.options.splitTheme="c";a.mobile.listview.prototype.options.countTheme="c";a.mobile.listview.prototype.options.filterTheme="c";a.mobile.listview.prototype.options.filterPlaceholder=a.i18n("dialog","filter");a.mobile.dialog.prototype.options.theme="d";a.mobile.dialog.prototype.options.closeBtnText=a.i18n("dialog","close");a.mobile.selectmenu.prototype.options.menuPageTheme=
"b";a.mobile.selectmenu.prototype.options.overlayTheme="b";a.mobile.selectmenu.prototype.options.closeText=a.i18n("dialog","close");a.mobile.loadingMessage=a.i18n("dialog","loading");a.mobile.loadingMessageTheme="a";a.mobile.pageLoadErrorMessage=a.i18n("dialog","error_page");a.mobile.pageLoadErrorMessageTheme="e"},init_dom:function(b){b=b?b+" ":'*[role="main"] ';a(b+"img").bind("taphold",function(){d.open(a(this).attr("src"))});a(b+"#contents ul").listview();this.glossaly(b);this.sh(b);this.bad_behavior(b);
this.tablesorter(b);a(b+"a").each(function(){var b=a(this),c=b.attr("href");b.data("ajax")&&b.data("ajax");c.match(/^#\w+?/)&&(b.data("ajax",!1),b.live("tap",function(){pukiwiki.anchor_scroll(c,!0);return!1}))})},tablesorter:function(){var b=this,c=function(b){return['<div class="table_pager_widget ui-helper-clearfix" id="'+b+'">','<div class="ui-corner-all ui-controlgroup ui-controlgroup-horizontal">','<a href="#" class="prev" data-role="button" data-icon="arrow-l" data-iconpos="notext">'+a.i18n("dialog",
"prev")+"</a>",'<input class="pagedisplay" type="text" disabled="disabled" size="8" />','<a href="#" class="next" data-role="button" data-icon="arrow-r" data-iconpos="notext">'+a.i18n("dialog","next")+"</a>",'<select class="pagesize"></select>\n</div>\n</div>'].join("\n")};a(".style_table").each(function(){var d=a(this);d.clone();var e=d.data(),f=b.config.tablesorter;if(!0!==d.data("enabled")){if(a("tr",this).length>f.pager.minimum_lines&&0!==a("thead",this).length){var g="table_pager_"+f.counter;
f.sorter.headers=e.headers;f.sorter.sortList=e.sortList;f.sorter.parsers=e.parsers;d.tablesorter(f.sorter);!0===f.pager.location_before?d.before(c(g)):d.after(c(g));for(e=0;e<f.pager.size.length;)a("#"+g+" .pagesize").append(a("<option>").attr({value:f.pager.size[e]}).text(f.pager.size[e])),e++;d.tablesorterPager({container:a("#"+g),positionFixed:!1,onthrough:function(a){b.glossaly(a)}});a("#"+g).show("clip");f.counter++}else d.tablesorter(f.sorter);d.data("enabled",!0)}})},glossaly:function(){a('[aria-describedby="tooltip"]:not(a)').each(function(){var b=
a(this),c=b.data("msgtext")?b.data("msgtext"):b.attr("title")?b.attr("title"):"";b.removeAttr("title");b.bind("tap",function(){a.mobile.showPageLoadingMsg();if(""===c){var d;a.ajax({url:SCRIPT,type:"GET",cache:!0,timeout:2E3,dataType:"xml",data:{cmd:"tooltip",q:b.text(),cache:!0},async:!1,success:function(b){d=b.documentElement.textContent;a.mobile.hidePageLoadingMsg()},complete:function(){c=d;b.data("msgtext",d);a.mobile.showPageLoadingMsg(a.mobile.page.prototype.options.headerTheme,d,!0);setTimeout(function(){a.mobile.hidePageLoadingMsg()},
3E3)}})}else a.mobile.showPageLoadingMsg(a.mobile.page.prototype.options.headerTheme,c,!0),setTimeout(function(){a.mobile.hidePageLoadingMsg()},3E3)})})},sh:function(b){b=b?b+" .sh":".sh";0!==a(b).length&&(this.config.syntaxhighlighter={baseUrl:JS_URI+"syntaxhighlighter/",target:b,config:{strings:{expandSource:a.i18n("sh","expandSource"),viewSource:a.i18n("sh","viewSource"),copyToClipboard:a.i18n("sh","copyToClipboard"),copyToClipboardConfirmation:a.i18n("sh","copyToClipboardConfirmation"),print:a.i18n("sh",
"print"),noBrush:a.i18n("sh","noBrush"),brushNotHtmlScript:a.i18n("sh","brushNotHtmlScript")}}},a.beautyOfCode.beautifyAll(this.config.syntaxhighlighter))},bad_behavior:function(b){"undefined"!==typeof BH_NAME&&"undefined"!==typeof BH_VALUE&&a((b?b+" ":"")+"form").append('<input type="hidden" name="'+BH_NAME+'" value="'+BH_VALUE+'" />')},anchor_scroll:function(b){b.match(/^#\w+?/)&&(b=b.split("#")[1],a.scrollTo("#"+b,{duration:800,axis:"y",queue:!0,onAfter:function(){}}))},register:{init:function(a){b.push(a)},
before_init:function(a){g.push(a)},unload:function(a){e.push(a)},before_unload:function(a){f.push(a)}}};a(c).ready(function(){"latest"!==JQUERY_MOBILE_VER?(a("head").append('<link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.mobile/'+JQUERY_MOBILE_VER+"/jquery.mobile-"+JQUERY_MOBILE_VER+'.min.css" />'),a.getScript("http://ajax.aspnetcdn.com/ajax/jquery.mobile/"+JQUERY_MOBILE_VER+"/jquery.mobile-"+JQUERY_MOBILE_VER+".min.js",function(){a("html").fadeIn("fast");a("html").css("display",
"block")})):(a("head").append('<link rel="stylesheet" href="http://code.jquery.com/mobile/latest/jquery.mobile.min.css" />'),a.getScript("http://code.jquery.com/mobile/latest/jquery.mobile.min.js",function(){a("html").fadeIn("fast");a("html").css("display","block")}))});a(c).bind("mobileinit",function(){var c=a('[data-role="page"]');if(DEBUG){var e=new Date;console.info("jQuery mobile loaded. (Process Time :",e-h,"ms)")}pukiwiki.init();c.live("pageload",function(){for(var a;a=g.shift();)null!==a&&
a()}).live("pageshow",function(){pukiwiki.init_dom();for(var a;a=b.shift();)null!==a&&a()});var f=a("#adarea_content");if(0!==f.length){var j=a("#adarea_content").find("iframe");a(j).appendTo(".adarea");f.remove();c.live("pagehide",function(){a(j).appendTo(".adarea")})}"undefined"!==typeof GOOGLE_ANALYTICS&&(d._gaq=[["_setAccount",GOOGLE_ANALYTICS],["_trackPageview"],["_trackPageLoadTime"]],$$page.live("pageshow",function(){_gaq.push(["_trackPageview",location.hash?location.hash:location.href])}),
a.getScript(("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js"));DEBUG&&(c=new Date,console.info("Finish. (Process Time :",c-e,"ms / Total :",c-h,"ms)"))})})(jQuery,this,this.document);
