<?php
/**
 * Visual Basic 2005
 */

//$capital = 1;                      // 予約語の大文字小文字を区別しない
$switchHash['"'] = PLUGIN_CODE_NONESCAPE_LITERAL;  // '"'は文字列区切り
$switchHash['#'] = PLUGIN_CODE_SPECIAL_IDENTIFIRE;  // # から始まる予約語あり

// コメント定義
$switchHash['\''] = PLUGIN_CODE_COMMENT;    // コメントは ' から改行まで
$switchHash['r'] = PLUGIN_CODE_COMMENT_WORD;   // コメントは REM から改行まで
$switchHash['R'] = PLUGIN_CODE_COMMENT_WORD;
$code_comment = Array(
	'\'' => Array(
				 Array('/^\'/', "\n", 1),
	    ),
	'r' => Array(
				 Array('/^rem\s/i', "\n", 1),
		),
	'R' => Array(
				 Array('/^rem\s/i', "\n", 1),
		),
);

$outline_def = Array(
					/*
					 'Do' => Array('Loop', 1),
					 'For' => Array('Next', 1),
					 'If' => Array('End If', 1),
					 'Select Case' => Array('End Select', 1),
					 'Try' => Array('End Try', 1),
					 'Using' => Array('End Using', 1),
					 'While' => Array('End While', 1),
					 'With' => Array('End With', 1),
					 '#Region' => Array('#End Region', 1),
					 */
					 );

$code_css = Array(
  'operator',		// オペレータ関数
  'identifier',	// その他の識別子
  'pragma',		// module, import と pragma
  'system',		// 処理系組み込みの奴 __stdcall とか
  );

$code_keyword = Array(
	'AddHandler' => 2,
	'AddressOf' => 2,
	'Alias' => 2,
	'And' => 2,
	'AndAlso' => 2,
	'Ansi' => 2,
	'As' => 2,
	'Assembly' => 2,
	'Auto' => 2,
	'Binary' => 2,
	'Boolean' => 2,
	'ByRef' => 2,
	'Byte' => 2,
	'ByVal' => 2,
	'Call' => 2,
	'Case' => 2,
	'Catch' => 2,
	'CBool' => 2,
	'CByte' => 2,
	'CChar' => 2,
	'CDate' => 2,
	'CDbl' => 2,
	'CDec' => 2,
	'Char' => 2,
	'CInt' => 2,
	'Class' => 2,
	'CLng' => 2,
	'CObj' => 2,
	'Compare' => 2,
	'Const' => 2,
	'Continue' => 2,
	'CSByte' => 2,
	'CShort' => 2,
	'CSng' => 2,
	'CStr' => 2,
	'CType' => 2,
	'CUInt' => 2,
	'CULng' => 2,
	'CUShort' => 2,
	'Custom' => 2,
	'Date' => 2,
	'Debug' => 2,
	'Decimal' => 2,
	'Declare' => 2,
	'Default' => 2,
	'Delegate' => 2,
	'Dim' => 2,
	'DirectCast' => 2,
	'Do' => 2,
	'Double' => 2,
	'Each' => 2,
	'Else' => 2,
	'ElseIf' => 2,
	'End' => 2,
	'EndIf' => 2,
	'Enum' => 2,
	'Erase' => 2,
	'Error' => 2,
	'Event' => 2,
	'Exit' => 2,
	'Explicit' => 2,
	'False' => 2,
	'Finally' => 2,
	'For' => 2,
	'Friend' => 2,
	'Function' => 2,
	'Get' => 2,
	'GetType' => 2,
	'Global' => 2,
	'GoSub' => 2,
	'GoTo' => 2,
	'Handles' => 2,
	'If' => 2,
	'Implements' => 2,
	'Imports' => 2,
	'In' => 2,
	'Inherits' => 2,
	'Integer' => 2,
	'Interface' => 2,
	'Is' => 2,
	'IsFalse' => 2,
	'IsNot' => 2,
	'IsTrue' => 2,
	'Let' => 2,
	'Lib' => 2,
	'Like' => 2,
	'Long' => 2,
	'Loop' => 2,
	'Me' => 2,
	'Mid' => 2,
	'Mod' => 2,
	'Module' => 2,
	'MustInherit' => 2,
	'MustOverride' => 2,
	'MyBase' => 2,
	'MyClass' => 2,
	'Namespace' => 2,
	'Narrowing' => 2,
	'New' => 2,
	'Next' => 2,
	'Not' => 2,
	'Nothing' => 2,
	'NotInheritable' => 2,
	'NotOverridable' => 2,
	'Object' => 2,
	'Of' => 2,
	'Off' => 2,
	'On' => 2,
	'Operator' => 2,
	'Option' => 2,
	'Optional' => 2,
	'Or' => 2,
	'OrElse' => 2,
	'Overloads' => 2,
	'Overridable' => 2,
	'Overrides' => 2,
	'ParamArray' => 2,
	'Partial' => 2,
	'Preserve' => 2,
	'Private' => 2,
	'Property' => 2,
	'Protected' => 2,
	'Public' => 2,
	'RaiseEvent' => 2,
	'ReadOnly' => 2,
	'ReDim' => 2,
	'RemoveHandler' => 2,
	'Resume' => 2,
	'Return' => 2,
	'SByte' => 2,
	'Select' => 2,
	'Set' => 2,
	'Shadows' => 2,
	'Shared' => 2,
	'Short' => 2,
	'Single' => 2,
	'Static' => 2,
	'Step' => 2,
	'Stop' => 2,
	'Strict' => 2,
	'String' => 2,
	'Structure' => 2,
	'Sub' => 2,
	'SyncLock' => 2,
	'Text' => 2,
	'Then' => 2,
	'Throw' => 2,
	'To' => 2,
	'True' => 2,
	'Try' => 2,
	'TryCast' => 2,
	'TypeOf' => 2,
	'UInteger' => 2,
	'ULong' => 2,
	'Unicode' => 2,
	'Until' => 2,
	'UShort' => 2,
	'Using' => 2,
	'Variant' => 2,
	'Wend' => 2,
	'When' => 2,
	'While' => 2,
	'Widening' => 2,
	'With' => 2,
	'WithEvents' => 2,
	'WriteOnly' => 2,
	'Xor' => 2,

	'#Const' => 3,
	'#Else' => 3,
	'#ElseIf' => 3,
	'#End' => 3,
	'Region' => 3,
	'#ExternalSource' => 3,
	'#If' => 3,
	'#Region' => 3,
  );
?>
